/**
 * Internacionalização do Simple Notes.
 *
 * Dicionários centralizados (pt-BR, en, es) + helper `t()`.
 * O idioma ativo fica persistido no Config (ThemeContext); qualquer tela que já
 * usa `useTheme()` ganha `t` sem novo provider.
 *
 * Convenção: a chave é o texto em PT-BR (fallback automático — se faltar a
 * tradução, o app mostra o PT em vez de quebrar). Chaves semânticas (ex.:
 * `tutorial.chave.passo1`) têm entrada explícita também no dicionário PT.
 */

export type Idioma = 'pt' | 'en' | 'es';

export const IDIOMAS: { cod: Idioma; rotulo: string }[] = [
  { cod: 'pt', rotulo: 'Português' },
  { cod: 'en', rotulo: 'English' },
  { cod: 'es', rotulo: 'Español' },
];

export const ehIdioma = (v: unknown): v is Idioma =>
  v === 'pt' || v === 'en' || v === 'es';

const pt: Record<string, string> = {
  // Chaves semânticas (não são o próprio texto)
  'tutorial.chave.passo1': 'Toque em “Abrir site” aqui embaixo — vai abrir o navegador no openrouter.ai',
  'tutorial.chave.passo2': 'Toque em “Continue with Google” e entre com sua conta (a mesma do app)',
  'tutorial.chave.passo3': 'Na página de chaves, toque em “+ Create Key” (deixe marcado “Free models”) e confirme',
  'tutorial.chave.passo4': 'O site mostra a chave (começa com sk-or-v1-). Toque e segure nela → Copiar',
  'tutorial.chave.passo5': 'Volte ao app e cole no campo acima — segure o dedo no campo e toque em “Colar”',
  // chaves da IA que são exibidas também em PT (a entrada explícita evita
  // mostrar o nome da chave cru se o texto PT divergir um dia)
};

const en: Record<string, string> = {
  // --- IA / assistente (respostas exibidas ao usuário) ---
  'Esse recurso não existe no Simple Notes: o app não exporta nem compartilha notas. Ele salva tudo automaticamente na sua conta Google (Drive). ✨': 'That feature does not exist in Simple Notes: the app does not export or share notes. It saves everything automatically to your Google account (Drive). ✨',
  'Sim! Em Ajustes → Anúncios há "Remover anúncios para sempre" (pagamento único pela Play Store). Também existe o Premium liberado por convite do desenvolvedor.': 'Yes! In Settings → Ads there is “Remove ads forever” (one-time payment via the Play Store). There is also Premium granted by a developer invite.',
  'Sim! Em Ajustes → Aparência você alterna o Modo Escuro.': 'Yes! In Settings → Appearance you can toggle Dark Mode.',
  'Em Ajustes → Alarme você escolhe o som do alarme, ajusta a soneca (5 a 60 min) e confere as permissões (popup em tela cheia, Xiaomi e bateria).': 'In Settings → Alarm you pick the alarm sound, adjust the snooze (5 to 60 min) and check the permissions (full-screen popup, Xiaomi and battery).',
  'Em Ajustes → Segurança, o app pode exigir biometria (digital ou rosto) ao abrir, com tempo de bloqueio de imediato até 30 minutos.': 'In Settings → Security, the app can require biometrics (fingerprint or face) when opening, with a lock timeout from immediate up to 30 minutes.',
  'Entrando com sua conta Google, notas, tarefas e a chave de IA ficam salvas no Drive com backup automático — ao trocar de aparelho, entre com a mesma conta e tudo volta.': 'When you sign in with your Google account, notes, tasks and the AI key are saved to Drive with automatic backup — when switching devices, sign in with the same account and everything comes back.',
  'Na aba Tarefas você cria tarefas com recorrência (uma vez, diária ou em dias específicos) e horário, marca como concluída e exclui. Cada tarefa dispara uma notificação no horário.': 'In the Tasks tab you can create tasks with recurrence (once, daily or on specific days) and a time, mark them done and delete them. Each task fires a notification at its time.',
  'Na tela principal, a fileira de pastas fica acima das notas: toque no sinal de + para criar uma pasta e, para mover itens, segure uma nota ou lista até entrar no modo de seleção — aí você escolhe vários itens e toca em "mover para pasta". Você também pode renomear a pasta abrindo-a.': 'On the home screen, the folder row sits above the notes: tap the + sign to create a folder, and to move items, press and hold a note or list to enter selection mode — then pick several items and tap “move to folder”. You can also rename a folder by opening it.',
  'As listas são checklists simples que aparecem junto das notas: crie pela tela principal, fixe as importantes, e elas também podem morar dentro de pastas (crie uma lista direto dentro da pasta).': 'Lists are simple checklists that appear alongside notes: create them from the home screen, pin the important ones, and they can also live inside folders (create a list right inside a folder).',
  'Em cada nota, o ícone de sino agenda lembretes: em data e horário, a cada X dias ou em dias da semana. Quando toca, o alarme abre em tela cheia com som e soneca.': 'In every note, the bell icon schedules reminders: on a date and time, every X days or on weekdays. When it rings, the alarm opens full screen with sound and snooze.',
  'A IA fica em Ajustes → IA: adicione a chave gratuita do OpenRouter (há o tutorial "Como criar a chave") para respostas completas sobre suas notas. Sem chave, respondo com buscas locais nas suas notas.': 'The AI lives in Settings → AI: add your free OpenRouter key (there is a “How to create the key” tutorial) for full answers about your notes. Without a key, I answer with local searches in your notes.',
  'No editor da nota você pode anexar imagens e gravar áudio. Em notas com anexos grandes, um botão (seta em círculo) leva você direto ao fim da nota.': 'In the note editor you can attach images and record audio. In notes with big attachments, a button (arrow in a circle) takes you straight to the end of the note.',
  'Em Ajustes → Aparência → Idioma você escolhe entre Português, English e Español — o app inteiro e o assistente de IA passam a responder no idioma escolhido.': 'In Settings → Appearance → Language you can choose between Português, English and Español — the whole app and the AI assistant switch to the language you pick.',
  'Você ainda não tem nenhuma nota ou tarefa. Crie uma nota ou tarefa primeiro e depois me pergunte! 📝✨': 'You do not have any notes or tasks yet. Create a note or task first, then ask me! 📝✨',
  'Só posso ajudar com assuntos sobre as suas notas e tarefas ✨\n\nNão encontrei nada relacionado à sua pergunta. Configure a chave gratuita de IA em Ajustes → IA para eu conseguir responder melhor.': 'I can only help with things about your notes and tasks ✨\n\nI found nothing related to your question. Set up the free AI key in Settings → AI so I can answer better.',
  'Encontrei isso nas suas notas e tarefas:': 'Here is what I found in your notes and tasks:',
  '(modo offline — adicione a chave gratuita de IA em Ajustes → IA para respostas completas como ChatGPT)': '(offline mode — add the free AI key in Settings → AI for full ChatGPT-like answers)',
  'Não consegui conectar à IA online agora, mas encontrei isto nas suas notas e tarefas:': 'I could not reach the online AI right now, but I found this in your notes and tasks:',
  '(Verifique sua internet ou a chave de IA em Ajustes.)': '(Check your internet or the AI key in Settings.)',
  'Não consegui conectar à IA online agora. Verifique sua internet ou a chave de IA em Ajustes → IA e tente de novo.': 'I could not reach the online AI right now. Check your internet or the AI key in Settings → AI and try again.',
  'A chave de IA configurada não é válida. Verifique em Ajustes → IA.': 'The AI key you entered is not valid. Check it in Settings → AI.',
  'A IA gratuita está com limite de uso no momento. Aguarde um minuto e tente de novo.': 'The free AI is rate-limited right now. Wait a minute and try again.',
  'A IA gratuita está com limite de uso no momento (muitas perguntas em pouco tempo). Aguarde um minuto e tente de novo — ou pergunte em Ajustes → IA se a chave está certa.': 'The free AI is rate-limited right now (too many questions in a short time). Wait a minute and try again — or check in Settings → AI whether the key is correct.',
  'Abra uma nota para eu resumir. ✍️': 'Open a note so I can summarize it. ✍️',
  'Para resumir com IA, configure sua chave gratuita em Ajustes → IA. 🔑': 'To summarize with AI, set up your free key in Settings → AI. 🔑',
  'Resuma esta nota:': 'Summarize this note:',
  'Sem título': 'Untitled',
  concluída: 'done',
  pendente: 'pending',
  'recorrência': 'recurrence',
  'horário': 'time',
  Tarefa: 'Task',
  'Tarefas:': 'Tasks:',
  'sem conteúdo': 'no content',
  // --- Editor / IA (chrome) ---
  'Desculpe, não consegui responder agora. Tente de novo.': 'Sorry, I could not answer right now. Try again.',
  'Não consegui gerar o resumo agora. Tente de novo.': 'I could not generate the summary right now. Try again.',
  Configurações: 'Settings',
  Aparência: 'Appearance',
  'Modo Escuro': 'Dark Mode',
  Idioma: 'Language',
  'Idioma do aplicativo e do assistente de IA': 'App and AI assistant language',
  'Escolha o idioma do aplicativo e do assistente de IA': 'Choose the language for the app and the AI assistant',
  'Português (padrão)': 'Portuguese (default)',
  Inglês: 'English',
  Espanhol: 'Spanish',
  Interface: 'Interface',
  'Ajuda no Menu +': 'Help in the + menu',
  'Mostrar botão de guia no menu de criação': 'Show a guide button in the create menu',
  Alarme: 'Alarm',
  'Som do alarme': 'Alarm sound',
  'Toca no volume de alarme, no máximo': 'Plays at the alarm volume, at maximum',
  'Soneca do alarme': 'Alarm snooze',
  'Tempo ao tocar em “Daqui a X min”': 'Delay when tapping “Snooze X min”',
  'Permissões do alarme': 'Alarm permissions',
  'Popup em tela cheia · Xiaomi · bateria': 'Full-screen popup · Xiaomi · battery',
  Anúncios: 'Ads',
  'Anúncios removidos': 'Ads removed',
  'Premium liberado por convite do desenvolvedor': 'Premium granted by a developer invite',
  'Obrigado pelo apoio! Sem anúncios para sempre': 'Thanks for your support! No ads forever',
  'Premium por convite': 'Premium by invite',
  'Remover anúncios para sempre': 'Remove ads forever',
  'Pagamento único pela Play Store': 'One-time payment via the Play Store',
  IA: 'AI',
  'Chave da IA (gratuita)': 'AI key (free)',
  'Respostas como ChatGPT usando modelos grátis do OpenRouter': 'Answers like ChatGPT using free OpenRouter models',
  'Como criar a chave': 'How to create the key',
  'Abrir site': 'Open site',
  'tutorial.chave.passo1': 'Tap “Open site” below — it opens your browser at openrouter.ai',
  'tutorial.chave.passo2': 'Tap “Continue with Google” and sign in with your account (the same one used in the app)',
  'tutorial.chave.passo3': 'On the keys page, tap “+ Create Key” (keep “Free models” checked) and confirm',
  'tutorial.chave.passo4': 'The site shows your key (it starts with sk-or-v1-). Press and hold it → Copy',
  'tutorial.chave.passo5': 'Return to the app and paste it into the field above — hold your finger on the field and tap “Paste”',
  'Entendi!': 'Got it!',
  'Versão do App': 'App version',
  Segurança: 'Security',
  'Bloquear App': 'Lock App',
  'Exigir biometria ao abrir o aplicativo': 'Require biometrics when opening the app',
  'Tempo de Bloqueio': 'Lock timeout',
  'Janela de carência antes de bloquear': 'Grace period before locking',
  Imediato: 'Immediate',
  Erro: 'Error',
  'Este dispositivo não possui suporte a biometria.': 'This device does not support biometrics.',
  'Nenhuma biometria (digital ou rosto) cadastrada no sistema.': 'No biometrics (fingerprint or face) enrolled on this device.',
  'Confirme sua identidade para ativar': 'Confirm your identity to enable',
  'Tempo para Bloqueio': 'Lock timeout',
  'Após quanto tempo fora do app devemos exigir a biometria?': 'After how long away from the app should we require biometrics?',
  Imediatamente: 'Immediately',
  '{n} minutos': '{n} minutes',
  '{n} min': '{n} min',
  'Quanto tempo o alarme adia ao tocar em "Daqui a X min"?': 'How long should the alarm snooze when you tap “Snooze X min”?',
  'Toca no volume de alarme do celular, forçado ao máximo': 'Plays at the phone alarm volume, forced to maximum',
  Clássico: 'Classic',
  Digital: 'Digital',
  Suave: 'Gentle',
  Urgente: 'Urgent',
  Eco: 'Echo',
  Ondas: 'Waves',
  'Bipes de despertador tradicionais': 'Traditional alarm beeps',
  'Toque de telefone digital': 'Digital phone ringtone',
  'Arpejo calmo para acordar devagar': 'Calm arpeggio to wake up slowly',
  'Bipes rápidos e fortes': 'Fast, loud beeps',
  'Melodia de cuco com eco': 'Cuckoo melody with echo',
  'Mar calmo batendo na areia': 'Calm sea washing onto the sand',
  'Criar sua chave grátis': 'Create your free key',
  'Leva 1 minuto e não pede cartão': 'Takes 1 minute and asks for no card',
  Negrito: 'Bold',
  Itálico: 'Italic',
  Sublinhado: 'Underline',
  Tachado: 'Strikethrough',
  'Lista com marcadores': 'Bulleted list',
  'Lista numerada': 'Numbered list',
  'Gravar áudio': 'Record audio',
  'Parar gravação': 'Stop recording',
  'Inserir imagem': 'Insert image',
  // --- Aba / rodapé ---
  Notas: 'Notes',
  Tarefas: 'Tasks',
  Ajustes: 'Settings',
  // --- Home / seleção / pastas ---
  Cancelar: 'Cancel',
  Excluir: 'Delete',
  'Excluir itens': 'Delete items',
  Criar: 'Create',
  'Criar pasta': 'Create folder',
  'Criar nova pasta...': 'Create new folder...',
  'Nova pasta': 'New folder',
  Pasta: 'Folder',
  'Nome da pasta': 'Folder name',
  'Mover para pasta': 'Move to folder',
  'Renomear pasta': 'Rename folder',
  Salvar: 'Save',
  Sucesso: 'Success',
  'Excluir pasta': 'Delete folder',
  'Apagar {n} item selecionado?': 'Delete {n} selected item?',
  'Apagar {n} itens selecionados?': 'Delete {n} selected items?',
  'Leva os {n} para dentro': 'Move the {n} in',
  'item selecionado': 'item selected',
  'itens selecionados': 'items selected',
  '{n} selecionada': '{n} selected',
  '{n} selecionadas': '{n} selected',
  'Deseja apagar esta nota?': 'Delete this note?',
  'Deseja apagar esta lista?': 'Delete this list?',
  'Nota sem título': 'Untitled note',
  'Lista sem título': 'Untitled list',
  'sem título': 'untitled',
  'Toque para editar...': 'Tap to edit...',
  'Nenhuma nota encontrada': 'No notes found',
  'Procurar em suas notas...': 'Search your notes...',
  'Comece a organizar suas ideias': 'Start organizing your ideas',
  'item salvo': 'item saved',
  'itens salvos': 'items saved',
  '{n} itens salvos': '{n} items saved',
  '{n} itens na lista': '{n} items in the list',
  'Toque no + para criar sua primeira nota': 'Tap + to create your first note',
  'Nenhuma pasta ainda — crie a primeira!': 'No folders yet — create your first one!',
  'Organize suas notas e listas em pastas': 'Organize your notes and lists in folders',
  'Guia Rápido': 'Quick guide',
  'Arraste para a': 'Swipe to the',
  Direita: 'right',
  Esquerda: 'left',
  'para fixar itens no topo': 'to pin items to the top',
  'para excluir uma nota': 'to delete a note',
  'Suas notas são salvas': 'Your notes are saved',
  automaticamente: 'automatically',
  'na sua conta Google': 'to your Google account',
  'Conectado como {nome}': 'Signed in as {nome}',
  Login: 'Sign in',
  'Entrar com Google': 'Sign in with Google',
  Sair: 'Log out',
  'Trocar Conta': 'Switch account',
  Usuário: 'User',
  Offline: 'Offline',
  'Sem sincronização': 'Not synced',
  'O login não foi concluído.': 'Sign-in was not completed.',
  'Login não concluído. Tente novamente.': 'Sign-in not completed. Try again.',
  'Falha no login': 'Sign-in failed',
  'Deseja realmente desconectar?': 'Do you really want to sign out?',
  'Você está offline. Conecte-se à internet para trocar de conta.': 'You are offline. Connect to the internet to switch accounts.',
  'Você precisa de internet para restaurar.': 'You need internet to restore.',
  'Dados restaurados!': 'Data restored!',
  'Falha ao restaurar.': 'Could not restore.',
  'Desconectado.': 'Signed out.',
  // --- Editor (chrome + lembretes) ---
  'Gravando...': 'Recording...',
  Pronto: 'Done',
  Editar: 'Edit',
  Título: 'Title',
  'Lembrete de revisão': 'Review reminder',
  'Me lembre de ver esta nota': 'Remind me to review this note',
  'A cada X dias': 'Every X days',
  'Dias da semana': 'Days of the week',
  Horário: 'Time',
  Data: 'Date',
  Escolher: 'Choose',
  Remover: 'Remove',
  'Falta o dia': 'Missing the date',
  'Escolha a data do lembrete.': 'Choose the reminder date.',
  'Faltam os dias': 'Missing the days',
  'Escolha pelo menos um dia da semana.': 'Pick at least one day of the week.',
  'Horário no passado': 'Time already passed',
  'Escolha uma data e horário futuros para o lembrete.': 'Pick a future date and time for the reminder.',
  'Permissão negada.': 'Permission denied.',
  'Permissão necessária.': 'Permission needed.',
  'Não foi possível iniciar a gravação.': 'Could not start recording.',
  'Falha ao salvar o áudio.': 'Could not save the audio.',
  'Não foi possível carregar a imagem.': 'Could not load the image.',
  'Notificações desativadas': 'Notifications disabled',
  'Permita as notificações nas configurações do aparelho para receber os lembretes das tarefas.': 'Allow notifications in the device settings to receive task reminders.',
  'Confirme para remover a proteção desta nota': 'Confirm to remove the protection from this note',
  // --- Editor: modal da IA ---
  'NotaIA': 'NotaIA',
  'Pergunte sobre suas notas': 'Ask about your notes',
  Perguntar: 'Ask',
  Resumo: 'Summary',
  'Pergunte sobre suas notas...': 'Ask about your notes...',
  'A conversa com IA precisa de chave': 'The AI chat requires a key',
  'Adicione sua chave gratuita em\nAjustes → IA para conversar com a IA de verdade.': 'Add your free key in\nSettings → AI to chat with the real AI.',
  'Ir para Ajustes': 'Go to Settings',
  'Pergunte qualquer coisa sobre suas notas. ✨\nEx.: «Quanto custa o arroz?» ou «Qual a data da festa?»': 'Ask anything about your notes. ✨\nE.g.: «How much is the rice?» or «What is the party date?»',
  'Resumindo…': 'Summarizing…',
  'Gerar resumo com IA': 'Generate AI summary',
  'Lembrete em {data} às {hora}': 'Reminder on {data} at {hora}',
  'Revisar a cada {n} dias às {hora}': 'Review every {n} days at {hora}',
  'Revisar às {hora}': 'Review at {hora}',
  'Revisar às {dias}, às {hora}': 'Review on {dias} at {hora}',
  // --- Editor de listas ---
  LISTA: 'LIST',
  'Título da lista': 'List title',
  'Adicionar item...': 'Add item...',
  'Progresso da lista': 'List progress',
  'Toque em um item para marcar como feito': 'Tap an item to mark it as done',
  'Sua lista está vazia': 'Your list is empty',
  'Adicione o primeiro item acima para começar.': 'Add your first item above to get started.',
  'Concluído': 'Done',
  Pendente: 'Pending',
  'Nova Lista': 'New List',
  // --- Aba de tarefas ---
  'Um passo de cada vez': 'One step at a time',
  'O que precisa ser feito?': 'What needs to be done?',
  'CONCLUÍDAS': 'DONE',
  'Tudo limpo por aqui!': 'All clear here!',
  'Adicione sua primeira tarefa acima.': 'Add your first task above.',
  'Uma vez': 'Once',
  Diária: 'Daily',
  Domingo: 'Sunday',
  Segunda: 'Monday',
  Terça: 'Tuesday',
  Quarta: 'Wednesday',
  Quinta: 'Thursday',
  Sexta: 'Friday',
  Sábado: 'Saturday',
  'Vou fazer': "I'll do it",
  'Deixar para depois': 'Remind me later',
  'Está na hora de revisar esta nota!': 'Time to review this note!',
  'Está na hora de fazer isso!': 'Time to do it!',
  'Daqui a {n} min': 'In {n} min',
  'Está na hora de: {titulo}': 'Time to: {titulo}',
  'Lembrete: {titulo}': 'Reminder: {titulo}',
  'Está na hora de revisar esta nota': 'Time to review this note',
  'Revisado': 'Reviewed',
  // --- Pasta (tela interna) ---
  'Pasta vazia': 'Empty folder',
  'Toque no + para criar uma nota ou lista aqui dentro': 'Tap + to create a note or list here',
  NOTAS: 'NOTES',
  LISTAS: 'LISTS',
  'Nenhum resultado': 'No results',
  'Nenhum item encontrado para &quot;{busca}&quot;': 'No items found for &quot;{busca}&quot;',
  Fixar: 'Pin',
  'Dê um novo nome para esta pasta': 'Give this folder a new name',
  '{n} item na pasta': '{n} item in the folder',
  '{n} itens na pasta': '{n} items in the folder',
  'Procurar nesta pasta...': 'Search in this folder...',
  'Excluir a pasta &quot;{nome}&quot;? As notas e listas dela voltam para a lista principal.': 'Delete the folder &quot;{nome}&quot;? Its notes and lists go back to the main list.',
  'Apagar a nota &quot;{titulo}&quot;?': 'Delete the note &quot;{titulo}&quot;?',
  'Apagar a lista &quot;{titulo}&quot;?': 'Delete the list &quot;{titulo}&quot;?',
  'Apagar {n} {qtd} selecionado{s}?': 'Delete {n} {qtd} selected{s}?',
  // --- Feedback ---
  'Como está usando o app?': 'How are you using the app?',
  'Seu feedback ajuda a melhorar o Simple Notes. Leva menos de um minuto!': 'Your feedback helps improve Simple Notes. It takes less than a minute!',
  'Avaliar no Google Play': 'Rate on Google Play',
  'Enviar feedback por e-mail': 'Send feedback by email',
  'Agora não': 'Not now',
  'Feedback — Simple Notes': 'Feedback — Simple Notes',
  'App Bloqueado': 'App Locked',
  'Desbloquear': 'Unlock',
  'Toque no botão abaixo para acessar suas notas, tarefas e anotações.': 'Tap the button below to access your notes, tasks and annotations.',
  'Bloqueio automático: imediato ao sair do app': 'Auto-lock: immediate when leaving the app',
  'Bloqueio automático: após {n} min fora do app': 'Auto-lock: after {n} min away from the app',
  'Acesse suas informações': 'Access your information',
  'Usar senha do dispositivo': 'Use device password',
  'Verificando permissões...': 'Checking permissions...',
  'Abrir': 'Open',
  'Notificações ativadas': 'Notifications enabled',
  'O app pode tocar o som do alarme': 'The app can play the alarm sound',
  'O app precisa da permissão para tocar o alarme': 'The app needs permission to play the alarm',
  'Alarme exato': 'Exact alarm',
  'O alarme dispara na hora certa': 'The alarm goes off on time',
  'Sem isso, o alarme pode atrasar alguns minutos': 'Without this, the alarm may be a few minutes late',
  'Exibir pop-ups em segundo plano (MIUI)': 'Show pop-ups in the background (MIUI)',
  'Popup liberado para abrir fora do app': 'Popup allowed to open outside the app',
  'Essencial no Xiaomi para o alarme abrir como popup (não só notificação)': 'Essential on Xiaomi for the alarm to open as a popup (not just a notification)',
  'Popup sobre outros apps': 'Popup over other apps',
  'O alarme abre por cima de tudo, mesmo com a tela ligada': 'The alarm opens above everything, even with the screen on',
  'Permite o alarme abrir por cima de outros apps': 'Allows the alarm to open over other apps',
  'Tela cheia (Android 14+)': 'Full screen (Android 14+)',
  'Pode abrir por cima de tudo, mesmo bloqueado': 'Can open above everything, even when locked',
  'Ative em Ajustes → Acesso especial → Tela cheia': 'Enable in Settings → Special access → Full screen',
  'Otimização de bateria': 'Battery optimization',
  'Sem restrições — alarme toca com o app fechado': 'Unrestricted — alarm rings with the app closed',
  'Defina "Sem restrições" para o alarme tocar com o app fechado': 'Set "Unrestricted" for the alarm to ring with the app closed',
  'Iniciar automaticamente (Autostart)': 'Start automatically (Autostart)',
  'Garante que o alarme dispare com o app fechado': 'Ensures the alarm fires with the app closed',
  'Ajustes → Apps → Gerenciar apps → Simple Notes → Iniciar automaticamente': 'Settings → Apps → Manage apps → Simple Notes → Start automatically',
  'Notificações na tela de bloqueio': 'Notifications on the lock screen',
  'Mostra o alarme com o celular bloqueado': 'Shows the alarm with the phone locked',
  'Ajustes → Notificações → Na tela de bloqueio → Mostrar tudo': 'Settings → Notifications → On the lock screen → Show all',
  'No Android, o alarme só abre em POPUP (por cima de outros apps) se o app tiver as permissões abaixo. Em aparelhos Xiaomi (MIUI/HyperOS) são necessários alguns passos extras.': 'On Android, the alarm only opens as a POPUP (over other apps) if the app has the permissions below. On Xiaomi devices (MIUI/HyperOS) some extra steps are needed.',
  'Com a permissão de popup (sobreposição) ativada, o alarme abre por cima de tudo — mesmo com a tela ligada. Sem ela: com a tela bloqueada/desligada abre em tela cheia; com a tela ligada mostra apenas um aviso no topo (toque nele para abrir o alarme).': 'With the popup (overlay) permission enabled, the alarm opens above everything — even with the screen on. Without it: with the screen locked/off it opens full screen; with the screen on it only shows a banner at the top (tap it to open the alarm).',
  'Dispositivo Xiaomi / MIUI detectado — ative os itens abaixo para o popup funcionar': 'Xiaomi / MIUI device detected — enable the items below for the popup to work',
  'Dica: se ainda assim o popup não abrir, verifique também em Ajustes → Bateria → Gerenciar bateria do aparelho se o app está como “Sem restrições” (o nome varia por fabricante: Samsung, Xiaomi, Motorola, etc.).': 'Tip: if the popup still does not open, also check in Settings → Battery → Manage battery whether the app is set to "Unrestricted" (the name varies by manufacturer: Samsung, Xiaomi, Motorola, etc.).',
  'Apagar': 'Delete',
  'Apagar áudio': 'Delete audio',
  'Deseja remover este áudio da nota?': 'Do you want to remove this audio from the note?',
  'Gravação de áudio': 'Audio recording',
  'Pausar áudio': 'Pause audio',
  'Reproduzir áudio': 'Play audio',
  '“Tela cheia” do Android 14+': '“Full screen” from Android 14+',
  '“Exibir pop-ups em segundo plano” do MIUI': '“Show pop-ups in the background” from MIUI',
  '“Exibir sobre outros apps”': '“Display over other apps”',
  'Popup do alarme bloqueado': 'Alarm popup blocked',
  'Para o alarme abrir em POPUP (por cima de outros apps, mesmo com o celular bloqueado), ative: {itens}.': 'For the alarm to open as a POPUP (over other apps, even with the phone locked), enable: {itens}.',
  ' No Xiaomi, ative também “Iniciar automaticamente” e “Sem restrições” na bateria.': ' On Xiaomi, also enable “Start automatically” and “Unrestricted” in battery.',
  'Abrir permissões': 'Open permissions',
};

const es: Record<string, string> = {
  // --- IA / assistente (respostas exibidas ao usuário) ---
  'Você ainda não tem nenhuma nota ou tarefa. Crie uma nota ou tarefa primeiro e depois me pergunte! 📝✨': 'Aún no tienes ninguna nota ni tarea. ¡Crea una nota o tarea primero y después pregúntame! 📝✨',
  'Esse recurso não existe no Simple Notes: o app não exporta nem compartilha notas. Ele salva tudo automaticamente na sua conta Google (Drive). ✨': 'Esa función no existe en Simple Notes: la app no exporta ni comparte notas. Guarda todo automáticamente en tu cuenta de Google (Drive). ✨',
  'Sim! Em Ajustes → Anúncios há "Remover anúncios para sempre" (pagamento único pela Play Store). Também existe o Premium liberado por convite do desenvolvedor.': '¡Sí! En Configuración → Anuncios tienes “Quitar anuncios para siempre” (pago único por Google Play). También existe el Premium otorgado por invitación del desarrollador.',
  'Sim! Em Ajustes → Aparência você alterna o Modo Escuro.': '¡Sí! En Configuración → Apariencia puedes alternar el modo oscuro.',
  'Em Ajustes → Alarme você escolhe o som do alarme, ajusta a soneca (5 a 60 min) e confere as permissões (popup em tela cheia, Xiaomi e bateria).': 'En Configuración → Alarma eliges el sonido de la alarma, ajustas la posposición (5 a 60 min) y revisas los permisos (popup a pantalla completa, Xiaomi y batería).',
  'Em Ajustes → Segurança, o app pode exigir biometria (digital ou rosto) ao abrir, com tempo de bloqueio de imediato até 30 minutos.': 'En Configuración → Seguridad, la app puede exigir biometría (huella o rostro) al abrir, con un tiempo de bloqueo desde inmediato hasta 30 minutos.',
  'Entrando com sua conta Google, notas, tarefas e a chave de IA ficam salvas no Drive com backup automático — ao trocar de aparelho, entre com a mesma conta e tudo volta.': 'Al iniciar sesión con tu cuenta de Google, las notas, tareas y la clave de IA se guardan en Drive con copia de seguridad automática; al cambiar de móvil, entra con la misma cuenta y todo vuelve.',
  'Na aba Tarefas você cria tarefas com recorrência (uma vez, diária ou em dias específicos) e horário, marca como concluída e exclui. Cada tarefa dispara uma notificação no horário.': 'En la pestaña Tareas creas tareas con repetición (una vez, diaria o en días concretos) y hora, las marcas como hechas y las eliminas. Cada tarea dispara una notificación a su hora.',
  'Na tela principal, a fileira de pastas fica acima das notas: toque no sinal de + para criar uma pasta e, para mover itens, segure uma nota ou lista até entrar no modo de seleção — aí você escolhe vários itens e toca em "mover para pasta". Você também pode renomear a pasta abrindo-a.': 'En la pantalla principal, la fila de carpetas está sobre las notas: toca el signo + para crear una carpeta y, para mover elementos, mantén pulsada una nota o lista hasta entrar en el modo de selección; ahí eliges varios elementos y tocas “mover a carpeta”. También puedes renombrar la carpeta abriéndola.',
  'As listas são checklists simples que aparecem junto das notas: crie pela tela principal, fixe as importantes, e elas também podem morar dentro de pastas (crie uma lista direto dentro da pasta).': 'Las listas son checklists sencillos que aparecen junto a las notas: créalas desde la pantalla principal, fija las importantes y también pueden vivir dentro de carpetas (crea una lista directamente dentro de la carpeta).',
  'Em cada nota, o ícone de sino agenda lembretes: em data e horário, a cada X dias ou em dias da semana. Quando toca, o alarme abre em tela cheia com som e soneca.': 'En cada nota, el icono de campana agenda recordatorios: en fecha y hora, cada X días o en días de la semana. Al sonar, la alarma se abre a pantalla completa con sonido y posposición.',
  'A IA fica em Ajustes → IA: adicione a chave gratuita do OpenRouter (há o tutorial "Como criar a chave") para respostas completas sobre suas notas. Sem chave, respondo com buscas locais nas suas notas.': 'La IA está en Configuración → IA: añade la clave gratuita de OpenRouter (hay un tutorial “Cómo crear la clave”) para respuestas completas sobre tus notas. Sin clave, respondo con búsquedas locales en tus notas.',
  'No editor da nota você pode anexar imagens e gravar áudio. Em notas com anexos grandes, um botão (seta em círculo) leva você direto ao fim da nota.': 'En el editor de la nota puedes adjuntar imágenes y grabar audio. En notas con adjuntos grandes, un botón (flecha en círculo) te lleva directo al final de la nota.',
  'Em Ajustes → Aparência → Idioma você escolhe entre Português, English e Español — o app inteiro e o assistente de IA passam a responder no idioma escolhido.': 'En Configuración → Apariencia → Idioma eliges entre Português, English y Español: toda la app y el asistente de IA pasan a responder en el idioma elegido.',
  'Só posso ajudar com assuntos sobre as suas notas e tarefas ✨\n\nNão encontrei nada relacionado à sua pergunta. Configure a chave gratuita de IA em Ajustes → IA para eu conseguir responder melhor.': 'Solo puedo ayudar con asuntos sobre tus notas y tareas ✨\n\nNo encontré nada relacionado con tu pregunta. Configura la clave gratuita de IA en Configuración → IA para que pueda responder mejor.',
  'Encontrei isso nas suas notas e tarefas:': 'Esto es lo que encontré en tus notas y tareas:',
  '(modo offline — adicione a chave gratuita de IA em Ajustes → IA para respostas completas como ChatGPT)': '(modo sin conexión: añade la clave gratuita de IA en Configuración → IA para respuestas completas como ChatGPT)',
  'Não consegui conectar à IA online agora, mas encontrei isto nas suas notas e tarefas:': 'No pude conectar con la IA en línea ahora, pero encontré esto en tus notas y tareas:',
  '(Verifique sua internet ou a chave de IA em Ajustes.)': '(Revisa tu conexión o la clave de IA en Configuración.)',
  'Não consegui conectar à IA online agora. Verifique sua internet ou a chave de IA em Ajustes → IA e tente de novo.': 'No pude conectar con la IA en línea ahora. Revisa tu conexión o la clave de IA en Configuración → IA e inténtalo de nuevo.',
  'A chave de IA configurada não é válida. Verifique em Ajustes → IA.': 'La clave de IA configurada no es válida. Revísala en Configuración → IA.',
  'A IA gratuita está com limite de uso no momento. Aguarde um minuto e tente de novo.': 'La IA gratuita tiene límite de uso ahora mismo. Espera un minuto e inténtalo de nuevo.',
  'A IA gratuita está com limite de uso no momento (muitas perguntas em pouco tempo). Aguarde um minuto e tente de novo — ou pergunte em Ajustes → IA se a chave está certa.': 'La IA gratuita tiene límite de uso ahora mismo (muchas preguntas en poco tiempo). Espera un minuto e inténtalo de nuevo, o revisa en Configuración → IA si la clave es correcta.',
  'Abra uma nota para eu resumir. ✍️': 'Abre una nota para que la resuma. ✍️',
  'Para resumir com IA, configure sua chave gratuita em Ajustes → IA. 🔑': 'Para resumir con IA, configura tu clave gratuita en Configuración → IA. 🔑',
  'Resuma esta nota:': 'Resume esta nota:',
  'Sem título': 'Sin título',
  concluída: 'completada',
  pendente: 'pendiente',
  'recorrência': 'repetición',
  'horário': 'hora',
  Tarefa: 'Tarea',
  'Tarefas:': 'Tareas:',
  'sem conteúdo': 'sin contenido',
  // --- Editor / IA (chrome) ---
  'Desculpe, não consegui responder agora. Tente de novo.': 'Lo siento, no pude responder ahora. Inténtalo de nuevo.',
  'Não consegui gerar o resumo agora. Tente de novo.': 'No pude generar el resumen ahora. Inténtalo de nuevo.',
  Configurações: 'Configuración',
  Aparência: 'Apariencia',
  'Modo Escuro': 'Modo oscuro',
  Idioma: 'Idioma',
  'Idioma do aplicativo e do assistente de IA': 'Idioma de la app y del asistente de IA',
  'Escolha o idioma do aplicativo e do assistente de IA': 'Elige el idioma de la app y del asistente de IA',
  'Português (padrão)': 'Portugués (predeterminado)',
  Inglês: 'Inglés',
  Espanhol: 'Español',
  Interface: 'Interfaz',
  'Ajuda no Menu +': 'Ayuda en el menú +',
  'Mostrar botão de guia no menu de criação': 'Mostrar un botón de guía en el menú de creación',
  Alarme: 'Alarma',
  'Som do alarme': 'Sonido de alarma',
  'Toca no volume de alarme, no máximo': 'Suena al volumen de alarma, al máximo',
  'Soneca do alarme': 'Posponer alarma',
  'Tempo ao tocar em “Daqui a X min”': 'Tiempo al tocar “Posponer X min”',
  'Permissões do alarme': 'Permisos de alarma',
  'Popup em tela cheia · Xiaomi · bateria': 'Popup a pantalla completa · Xiaomi · batería',
  Anúncios: 'Anuncios',
  'Anúncios removidos': 'Anuncios eliminados',
  'Premium liberado por convite do desenvolvedor': 'Premium otorgado por invitación del desarrollador',
  'Obrigado pelo apoio! Sem anúncios para sempre': '¡Gracias por tu apoyo! Sin anuncios para siempre',
  'Premium por convite': 'Premium por invitación',
  'Remover anúncios para sempre': 'Quitar anuncios para siempre',
  'Pagamento único pela Play Store': 'Pago único por Google Play',
  IA: 'IA',
  'Chave da IA (gratuita)': 'Clave de IA (gratuita)',
  'Respostas como ChatGPT usando modelos grátis do OpenRouter': 'Respuestas como ChatGPT con modelos gratis de OpenRouter',
  'Como criar a chave': 'Cómo crear la clave',
  'Abrir site': 'Abrir sitio web',
  'tutorial.chave.passo1': 'Toca “Abrir sitio web” abajo: se abrirá el navegador en openrouter.ai',
  'tutorial.chave.passo2': 'Toca “Continue with Google” e inicia sesión con tu cuenta (la misma de la app)',
  'tutorial.chave.passo3': 'En la página de claves, toca “+ Create Key” (mantén marcado “Free models”) y confirma',
  'tutorial.chave.passo4': 'El sitio muestra tu clave (empieza con sk-or-v1-). Mantén pulsada y toca → Copiar',
  'tutorial.chave.passo5': 'Vuelve a la app y pega la clave en el campo de arriba: mantén el dedo en el campo y toca “Pegar”',
  'Entendi!': '¡Entendido!',
  'Versão do App': 'Versión de la app',
  Segurança: 'Seguridad',
  'Bloquear App': 'Bloquear la app',
  'Exigir biometria ao abrir o aplicativo': 'Exigir biometría al abrir la app',
  'Tempo de Bloqueio': 'Tiempo de bloqueo',
  'Janela de carência antes de bloquear': 'Periodo de gracia antes de bloquear',
  Imediato: 'Inmediato',
  Erro: 'Error',
  'Este dispositivo não possui suporte a biometria.': 'Este dispositivo no admite biometría.',
  'Nenhuma biometria (digital ou rosto) cadastrada no sistema.': 'No hay biometría (huella o rostro) registrada en el sistema.',
  'Confirme sua identidade para ativar': 'Confirma tu identidad para activar',
  'Tempo para Bloqueio': 'Tiempo de bloqueo',
  'Após quanto tempo fora do app devemos exigir a biometria?': '¿Después de cuánto tiempo fuera de la app exigimos la biometría?',
  Imediatamente: 'Inmediatamente',
  '{n} minutos': '{n} minutos',
  '{n} min': '{n} min',
  'Quanto tempo o alarme adia ao tocar em "Daqui a X min"?': '¿Cuánto tiempo pospone la alarma al tocar “Posponer X min”?',
  'Toca no volume de alarme do celular, forçado ao máximo': 'Suena al volumen de alarma del móvil, forzado al máximo',
  Clássico: 'Clásico',
  Digital: 'Digital',
  Suave: 'Suave',
  Urgente: 'Urgente',
  Eco: 'Eco',
  Ondas: 'Olas',
  'Bipes de despertador tradicionais': 'Bips de despertador tradicionales',
  'Toque de telefone digital': 'Timbre de teléfono digital',
  'Arpejo calmo para acordar devagar': 'Arpegio tranquilo para despertar despacio',
  'Bipes rápidos e fortes': 'Bips rápidos y fuertes',
  'Melodia de cuco com eco': 'Melodía de cuco con eco',
  'Mar calmo batendo na areia': 'Mar en calma llegando a la arena',
  'Criar sua chave grátis': 'Crea tu clave gratis',
  'Leva 1 minuto e não pede cartão': 'Toma 1 minuto y no pide tarjeta',
  Negrito: 'Negrita',
  Itálico: 'Cursiva',
  Sublinhado: 'Subrayado',
  Tachado: 'Tachado',
  'Lista com marcadores': 'Lista con viñetas',
  'Lista numerada': 'Lista numerada',
  'Gravar áudio': 'Grabar audio',
  'Parar gravação': 'Detener grabación',
  'Inserir imagem': 'Insertar imagen',
  // --- Aba / rodapé ---
  Notas: 'Notas',
  Tarefas: 'Tareas',
  Ajustes: 'Configuración',
  // --- Home / seleção / pastas ---
  Cancelar: 'Cancelar',
  Excluir: 'Eliminar',
  'Excluir itens': 'Eliminar elementos',
  Criar: 'Crear',
  'Criar pasta': 'Crear carpeta',
  'Criar nova pasta...': 'Crear nueva carpeta...',
  'Nova pasta': 'Nueva carpeta',
  Pasta: 'Carpeta',
  'Nome da pasta': 'Nombre de la carpeta',
  'Mover para pasta': 'Mover a carpeta',
  'Renomear pasta': 'Renombrar carpeta',
  Salvar: 'Guardar',
  Sucesso: 'Éxito',
  'Excluir pasta': 'Eliminar carpeta',
  'Apagar {n} item selecionado?': '¿Eliminar {n} elemento seleccionado?',
  'Apagar {n} itens selecionados?': '¿Eliminar {n} elementos seleccionados?',
  'Leva os {n} para dentro': 'Mete los {n} dentro',
  'item selecionado': 'elemento seleccionado',
  'itens selecionados': 'elementos seleccionados',
  '{n} selecionada': '{n} seleccionada',
  '{n} selecionadas': '{n} seleccionadas',
  'Deseja apagar esta nota?': '¿Eliminar esta nota?',
  'Deseja apagar esta lista?': '¿Eliminar esta lista?',
  'Nota sem título': 'Nota sin título',
  'Lista sem título': 'Lista sin título',
  'sem título': 'sin título',
  'Toque para editar...': 'Toca para editar...',
  'Nenhuma nota encontrada': 'No se encontraron notas',
  'Procurar em suas notas...': 'Buscar en tus notas...',
  'Comece a organizar suas ideias': 'Empieza a organizar tus ideas',
  'item salvo': 'elemento guardado',
  'itens salvos': 'elementos guardados',
  '{n} itens salvos': '{n} elementos guardados',
  '{n} itens na lista': '{n} elementos en la lista',
  'Toque no + para criar sua primeira nota': 'Toca + para crear tu primera nota',
  'Nenhuma pasta ainda — crie a primeira!': 'Aún no hay carpetas: ¡crea la primera!',
  'Organize suas notas e listas em pastas': 'Organiza tus notas y listas en carpetas',
  'Guia Rápido': 'Guía rápida',
  'Arraste para a': 'Desliza hacia la',
  Direita: 'derecha',
  Esquerda: 'izquierda',
  'para fixar itens no topo': 'para fijar elementos arriba',
  'para excluir uma nota': 'para eliminar una nota',
  'Suas notas são salvas': 'Tus notas se guardan',
  automaticamente: 'automáticamente',
  'na sua conta Google': 'en tu cuenta de Google',
  'Conectado como {nome}': 'Conectado como {nome}',
  Login: 'Iniciar sesión',
  'Entrar com Google': 'Iniciar sesión con Google',
  Sair: 'Cerrar sesión',
  'Trocar Conta': 'Cambiar de cuenta',
  Usuário: 'Usuario',
  Offline: 'Sin conexión',
  'Sem sincronização': 'Sin sincronizar',
  'O login não foi concluído.': 'El inicio de sesión no se completó.',
  'Login não concluído. Tente novamente.': 'Inicio de sesión no completado. Inténtalo de nuevo.',
  'Falha no login': 'Error al iniciar sesión',
  'Deseja realmente desconectar?': '¿De verdad quieres cerrar la sesión?',
  'Você está offline. Conecte-se à internet para trocar de conta.': 'Estás sin conexión. Conéctate a internet para cambiar de cuenta.',
  'Você precisa de internet para restaurar.': 'Necesitas internet para restaurar.',
  'Dados restaurados!': '¡Datos restaurados!',
  'Falha ao restaurar.': 'No se pudo restaurar.',
  'Desconectado.': 'Sesión cerrada.',
  // --- Editor (chrome + lembretes) ---
  'Gravando...': 'Grabando...',
  Pronto: 'Listo',
  Editar: 'Editar',
  Título: 'Título',
  'Lembrete de revisão': 'Recordatorio de revisión',
  'Me lembre de ver esta nota': 'Recuérdame revisar esta nota',
  'A cada X dias': 'Cada X días',
  'Dias da semana': 'Días de la semana',
  Horário: 'Hora',
  Data: 'Fecha',
  Escolher: 'Elegir',
  Remover: 'Quitar',
  'Falta o dia': 'Falta la fecha',
  'Escolha a data do lembrete.': 'Elige la fecha del recordatorio.',
  'Faltam os dias': 'Faltan los días',
  'Escolha pelo menos um dia da semana.': 'Elige al menos un día de la semana.',
  'Horário no passado': 'Hora ya pasada',
  'Escolha uma data e horário futuros para o lembrete.': 'Elige una fecha y hora futuras para el recordatorio.',
  'Permissão negada.': 'Permiso denegado.',
  'Permissão necessária.': 'Permiso necesario.',
  'Não foi possível iniciar a gravação.': 'No se pudo iniciar la grabación.',
  'Falha ao salvar o áudio.': 'No se pudo guardar el audio.',
  'Não foi possível carregar a imagem.': 'No se pudo cargar la imagen.',
  'Notificações desativadas': 'Notificaciones desactivadas',
  'Permita as notificações nas configurações do aparelho para receber os lembretes das tarefas.': 'Permite las notificaciones en la configuración del dispositivo para recibir los recordatorios de las tareas.',
  'Confirme para remover a proteção desta nota': 'Confirma para quitar la protección de esta nota',
  // --- Editor: modal da IA ---
  'NotaIA': 'NotaIA',
  'Pergunte sobre suas notas': 'Pregunta sobre tus notas',
  Perguntar: 'Preguntar',
  Resumo: 'Resumen',
  'Pergunte sobre suas notas...': 'Pregunta sobre tus notas...',
  'A conversa com IA precisa de chave': 'La conversación con IA necesita una clave',
  'Adicione sua chave gratuita em\nAjustes → IA para conversar com a IA de verdade.': 'Añade tu clave gratuita en\nConfiguración → IA para hablar con la IA de verdad.',
  'Ir para Ajustes': 'Ir a Configuración',
  'Pergunte qualquer coisa sobre suas notas. ✨\nEx.: «Quanto custa o arroz?» ou «Qual a data da festa?»': 'Pregunta lo que quieras sobre tus notas. ✨\nEj.: «¿Cuánto cuesta el arroz?» o «¿Cuál es la fecha de la fiesta?»',
  'Resumindo…': 'Resumiendo…',
  'Gerar resumo com IA': 'Generar resumen con IA',
  'Lembrete em {data} às {hora}': 'Recordatorio el {data} a las {hora}',
  'Revisar a cada {n} dias às {hora}': 'Revisar cada {n} días a las {hora}',
  'Revisar às {hora}': 'Revisar a las {hora}',
  'Revisar às {dias}, às {hora}': 'Revisar los {dias} a las {hora}',
  // --- Editor de listas ---
  LISTA: 'LISTA',
  'Título da lista': 'Título de la lista',
  'Adicionar item...': 'Añadir elemento...',
  'Progresso da lista': 'Progreso de la lista',
  'Toque em um item para marcar como feito': 'Toca un elemento para marcarlo como hecho',
  'Sua lista está vazia': 'Tu lista está vacía',
  'Adicione o primeiro item acima para começar.': 'Añade el primer elemento arriba para empezar.',
  'Concluído': 'Hecho',
  Pendente: 'Pendiente',
  'Nova Lista': 'Nueva lista',
  // --- Aba de tarefas ---
  'Um passo de cada vez': 'Un paso a la vez',
  'O que precisa ser feito?': '¿Qué hay que hacer?',
  'CONCLUÍDAS': 'HECHAS',
  'Tudo limpo por aqui!': '¡Todo limpio por aquí!',
  'Adicione sua primeira tarefa acima.': 'Añade tu primera tarea arriba.',
  'Uma vez': 'Una vez',
  Diária: 'Diaria',
  Domingo: 'Domingo',
  Segunda: 'Lunes',
  Terça: 'Martes',
  Quarta: 'Miércoles',
  Quinta: 'Jueves',
  Sexta: 'Viernes',
  Sábado: 'Sábado',
  'Vou fazer': 'Lo haré',
  'Deixar para depois': 'Dejarlo para después',
  'Está na hora de revisar esta nota!': '¡Es hora de revisar esta nota!',
  'Está na hora de fazer isso!': '¡Es hora de hacerlo!',
  'Daqui a {n} min': 'Dentro de {n} min',
  'Está na hora de: {titulo}': 'Es hora de: {titulo}',
  'Lembrete: {titulo}': 'Recordatorio: {titulo}',
  'Está na hora de revisar esta nota': 'Es hora de revisar esta nota',
  'Revisado': 'Revisado',
  // --- Pasta (tela interna) ---
  'Pasta vazia': 'Carpeta vacía',
  'Toque no + para criar uma nota ou lista aqui dentro': 'Toca + para crear una nota o lista aquí',
  NOTAS: 'NOTAS',
  LISTAS: 'LISTAS',
  'Nenhum resultado': 'Sin resultados',
  'Nenhum item encontrado para &quot;{busca}&quot;': 'No se encontraron elementos para &quot;{busca}&quot;',
  Fixar: 'Fijar',
  'Dê um novo nome para esta pasta': 'Ponle un nuevo nombre a esta carpeta',
  '{n} item na pasta': '{n} elemento en la carpeta',
  '{n} itens na pasta': '{n} elementos en la carpeta',
  'Procurar nesta pasta...': 'Buscar en esta carpeta...',
  'Excluir a pasta &quot;{nome}&quot;? As notas e listas dela voltam para a lista principal.': '¿Eliminar la carpeta &quot;{nome}&quot;? Sus notas y listas vuelven a la lista principal.',
  'Apagar a nota &quot;{titulo}&quot;?': '¿Eliminar la nota &quot;{titulo}&quot;?',
  'Apagar a lista &quot;{titulo}&quot;?': '¿Eliminar la lista &quot;{titulo}&quot;?',
  'Apagar {n} {qtd} selecionado{s}?': '¿Eliminar {n} {qtd} seleccionado{s}?',
  // --- Feedback ---
  'Como está usando o app?': '¿Cómo estás usando la app?',
  'Seu feedback ajuda a melhorar o Simple Notes. Leva menos de um minuto!': 'Tus comentarios ayudan a mejorar Simple Notes. ¡Toma menos de un minuto!',
  'Avaliar no Google Play': 'Valorar en Google Play',
  'Enviar feedback por e-mail': 'Enviar comentarios por correo',
  'Agora não': 'Ahora no',
  'Feedback — Simple Notes': 'Comentarios — Simple Notes',
  'App Bloqueado': 'App Bloqueada',
  'Desbloquear': 'Desbloquear',
  'Toque no botão abaixo para acessar suas notas, tarefas e anotações.': 'Toca el botón de abajo para acceder a tus notas, tareas y anotaciones.',
  'Bloqueio automático: imediato ao sair do app': 'Bloqueo automático: inmediato al salir de la app',
  'Bloqueio automático: após {n} min fora do app': 'Bloqueo automático: después de {n} min fuera de la app',
  'Acesse suas informações': 'Accede a tu información',
  'Usar senha do dispositivo': 'Usar contraseña del dispositivo',
  'Verificando permissões...': 'Verificando permisos...',
  'Abrir': 'Abrir',
  'Notificações ativadas': 'Notificaciones activadas',
  'O app pode tocar o som do alarme': 'La app puede reproducir el sonido de la alarma',
  'O app precisa da permissão para tocar o alarme': 'La app necesita permiso para reproducir la alarma',
  'Alarme exato': 'Alarma exacta',
  'O alarme dispara na hora certa': 'La alarma suena a tiempo',
  'Sem isso, o alarme pode atrasar alguns minutos': 'Sin esto, la alarma puede retrasarse unos minutos',
  'Exibir pop-ups em segundo plano (MIUI)': 'Mostrar ventanas emergentes en segundo plano (MIUI)',
  'Popup liberado para abrir fora do app': 'Ventana emergente permitida para abrir fuera de la app',
  'Essencial no Xiaomi para o alarme abrir como popup (não só notificação)': 'Esencial en Xiaomi para que la alarma se abra como ventana emergente (no solo notificación)',
  'Popup sobre outros apps': 'Ventana emergente sobre otras apps',
  'O alarme abre por cima de tudo, mesmo com a tela ligada': 'La alarma se abre por encima de todo, incluso con la pantalla encendida',
  'Permite o alarme abrir por cima de outros apps': 'Permite que la alarma se abra sobre otras apps',
  'Tela cheia (Android 14+)': 'Pantalla completa (Android 14+)',
  'Pode abrir por cima de tudo, mesmo bloqueado': 'Puede abrirse por encima de todo, incluso bloqueado',
  'Ative em Ajustes → Acesso especial → Tela cheia': 'Actívalo en Ajustes → Acceso especial → Pantalla completa',
  'Otimização de bateria': 'Optimización de batería',
  'Sem restrições — alarme toca com o app fechado': 'Sin restricciones — la alarma suena con la app cerrada',
  'Defina "Sem restrições" para o alarme tocar com o app fechado': 'Configura "Sin restricciones" para que la alarma suene con la app cerrada',
  'Iniciar automaticamente (Autostart)': 'Iniciar automáticamente (Autostart)',
  'Garante que o alarme dispare com o app fechado': 'Garantiza que la alarma suene con la app cerrada',
  'Ajustes → Apps → Gerenciar apps → Simple Notes → Iniciar automaticamente': 'Ajustes → Apps → Gestionar apps → Simple Notes → Iniciar automáticamente',
  'Notificações na tela de bloqueio': 'Notificaciones en la pantalla de bloqueo',
  'Mostra o alarme com o celular bloqueado': 'Muestra la alarma con el teléfono bloqueado',
  'Ajustes → Notificações → Na tela de bloqueio → Mostrar tudo': 'Ajustes → Notificaciones → En la pantalla de bloqueo → Mostrar todo',
  'No Android, o alarme só abre em POPUP (por cima de outros apps) se o app tiver as permissões abaixo. Em aparelhos Xiaomi (MIUI/HyperOS) são necessários alguns passos extras.': 'En Android, la alarma solo se abre en POPUP (sobre otras apps) si la app tiene los permisos de abajo. En dispositivos Xiaomi (MIUI/HyperOS) se necesitan algunos pasos extra.',
  'Com a permissão de popup (sobreposição) ativada, o alarme abre por cima de tudo — mesmo com a tela ligada. Sem ela: com a tela bloqueada/desligada abre em tela cheia; com a tela ligada mostra apenas um aviso no topo (toque nele para abrir o alarme).': 'Con el permiso de ventana emergente (superposición) activado, la alarma se abre por encima de todo — incluso con la pantalla encendida. Sin él: con la pantalla bloqueada/apagada se abre a pantalla completa; con la pantalla encendida solo muestra un aviso arriba (toca para abrir la alarma).',
  'Dispositivo Xiaomi / MIUI detectado — ative os itens abaixo para o popup funcionar': 'Dispositivo Xiaomi / MIUI detectado — activa los elementos de abajo para que funcione la ventana emergente',
  'Dica: se ainda assim o popup não abrir, verifique também em Ajustes → Bateria → Gerenciar bateria do aparelho se o app está como “Sem restrições” (o nome varia por fabricante: Samsung, Xiaomi, Motorola, etc.).': 'Consejo: si la ventana emergente aún no se abre, revisa también en Ajustes → Batería → Administrar batería si la app está como "Sin restricciones" (el nombre varía según el fabricante: Samsung, Xiaomi, Motorola, etc.).',
  'Apagar': 'Eliminar',
  'Apagar áudio': 'Eliminar audio',
  'Deseja remover este áudio da nota?': '¿Quieres quitar este audio de la nota?',
  'Gravação de áudio': 'Grabación de audio',
  'Pausar áudio': 'Pausar audio',
  'Reproduzir áudio': 'Reproducir audio',
  '“Tela cheia” do Android 14+': '“Pantalla completa” de Android 14+',
  '“Exibir pop-ups em segundo plano” do MIUI': '“Mostrar ventanas emergentes en segundo plano” de MIUI',
  '“Exibir sobre outros apps”': '“Mostrar sobre otras apps”',
  'Popup do alarme bloqueado': 'Ventana emergente de alarma bloqueada',
  'Para o alarme abrir em POPUP (por cima de outros apps, mesmo com o celular bloqueado), ative: {itens}.': 'Para que la alarma se abra en POPUP (sobre otras apps, incluso con el teléfono bloqueado), activa: {itens}.',
  ' No Xiaomi, ative também “Iniciar automaticamente” e “Sem restrições” na bateria.': ' En Xiaomi, activa también “Iniciar automáticamente” y “Sin restricciones” en la batería.',
  'Abrir permissões': 'Abrir permisos',
};

export const traducoes: Record<Idioma, Record<string, string>> = { pt, en, es };

/**
 * Idioma ativo (espelho do config). Permite localizar strings fora de
 * componentes React (ex.: textos de notificação agendados em módulos puros).
 * O ThemeProvider atualiza este espelho sempre que o idioma muda.
 */
export let idiomaAtual: Idioma = 'pt';
export const definirIdiomaAtual = (i: Idioma) => {
  idiomaAtual = i;
};

/** Traduz uma chave para o idioma ativo (com fallback pt → chave). */
export function tIdioma(
  idioma: Idioma,
  chave: string,
  vars?: Record<string, string | number>
): string {
  let texto = traducoes[idioma][chave] ?? traducoes.pt[chave] ?? chave;
  if (vars) {
    for (const k of Object.keys(vars)) {
      texto = texto.split(`{${k}}`).join(String(vars[k]));
    }
  }
  return texto;
}
