/**
 * Internacionalização do Simple Notes.
 *
 * Dicionários centralizados (pt-BR, en, es) + helper `t()`.
 * O idioma ativo fica persistido no Config (ThemeContext); qualquer tela que já
 * usa `useTheme()` ganha `t` sem novo provider.
 *
 * Convenção: a chave é o texto em PT-BR (fallback automático — se faltar a
 * tradução, o app mostra o PT em vez de quebrar). Chaves semânticas (ex.:
 * `tutorial.chave.passo1`) têm entrada explícita também no dicionário PT.
 */

export type Idioma = 'pt' | 'en' | 'es';

export const IDIOMAS: { cod: Idioma; rotulo: string }[] = [
  { cod: 'pt', rotulo: 'Português' },
  { cod: 'en', rotulo: 'English' },
  { cod: 'es', rotulo: 'Español' },
];

export const ehIdioma = (v: unknown): v is Idioma =>
  v === 'pt' || v === 'en' || v === 'es';

const pt: Record<string, string> = {
  // Chaves semânticas (não são o próprio texto)
  'tutorial.chave.passo1': 'Toque em “Abrir site” aqui embaixo — vai abrir o navegador no openrouter.ai',
  'tutorial.chave.passo2': 'Toque em “Continue with Google” e entre com sua conta (a mesma do app)',
  'tutorial.chave.passo3': 'Na página de chaves, toque em “+ Create Key” (deixe marcado “Free models”) e confirme',
  'tutorial.chave.passo4': 'O site mostra a chave (começa com sk-or-v1-). Toque e segure nela → Copiar',
  'tutorial.chave.passo5': 'Volte ao app e cole no campo acima — segure o dedo no campo e toque em “Colar”',
  // chaves da IA que são exibidas também em PT (a entrada explícita evita
  // mostrar o nome da chave cru se o texto PT divergir um dia)
};

const en: Record<string, string> = {
  // --- IA / assistente (respostas exibidas ao usuário) ---
  'Esse recurso não existe no Simple Notes: o app não exporta nem compartilha notas. Ele salva tudo automaticamente na sua conta Google (Drive). ✨': 'That feature does not exist in Simple Notes: the app does not export or share notes. It saves everything automatically to your Google account (Drive). ✨',
  'Sim! Em Ajustes → Anúncios há "Remover anúncios para sempre" (pagamento único pela Play Store). Também existe o Premium liberado por convite do desenvolvedor.': 'Yes! In Settings → Ads there is “Remove ads forever” (one-time payment via the Play Store). There is also Premium granted by a developer invite.',
  'Sim! Em Ajustes → Aparência você alterna o Modo Escuro.': 'Yes! In Settings → Appearance you can toggle Dark Mode.',
  'Em Ajustes → Alarme você escolhe o som do alarme, ajusta a soneca (5 a 60 min) e confere as permissões (popup em tela cheia, Xiaomi e bateria).': 'In Settings → Alarm you pick the alarm sound, adjust the snooze (5 to 60 min) and check the permissions (full-screen popup, Xiaomi and battery).',
  'Em Ajustes → Segurança, o app pode exigir biometria (digital ou rosto) ao abrir, com tempo de bloqueio de imediato até 30 minutos.': 'In Settings → Security, the app can require biometrics (fingerprint or face) when opening, with a lock timeout from immediate up to 30 minutes.',
  'Entrando com sua conta Google, notas, tarefas e a chave de IA ficam salvas no Drive com backup automático — ao trocar de aparelho, entre com a mesma conta e tudo volta.': 'When you sign in with your Google account, notes, tasks and the AI key are saved to Drive with automatic backup — when switching devices, sign in with the same account and everything comes back.',
  'Na aba Tarefas você cria tarefas com recorrência (uma vez, diária ou em dias específicos) e horário, marca como concluída e exclui. Cada tarefa dispara uma notificação no horário.': 'In the Tasks tab you can create tasks with recurrence (once, daily or on specific days) and a time, mark them done and delete them. Each task fires a notification at its time.',
  'Na tela principal, a fileira de pastas fica acima das notas: toque no sinal de + para criar uma pasta e, para mover itens, segure uma nota ou lista até entrar no modo de seleção — aí você escolhe vários itens e toca em "mover para pasta". Você também pode renomear a pasta abrindo-a.': 'On the home screen, the folder row sits above the notes: tap the + sign to create a folder, and to move items, press and hold a note or list to enter selection mode — then pick several items and tap “move to folder”. You can also rename a folder by opening it.',
  'As listas são checklists simples que aparecem junto das notas: crie pela tela principal, fixe as importantes, e elas também podem morar dentro de pastas (crie uma lista direto dentro da pasta).': 'Lists are simple checklists that appear alongside notes: create them from the home screen, pin the important ones, and they can also live inside folders (create a list right inside a folder).',
  'Em cada nota, o ícone de sino agenda lembretes: em data e horário, a cada X dias ou em dias da semana. Quando toca, o alarme abre em tela cheia com som e soneca.': 'In every note, the bell icon schedules reminders: on a date and time, every X days or on weekdays. When it rings, the alarm opens full screen with sound and snooze.',
  'A IA fica em Ajustes → IA: adicione a chave gratuita do OpenRouter (há o tutorial "Como criar a chave") para respostas completas sobre suas notas. Sem chave, respondo com buscas locais nas suas notas.': 'The AI lives in Settings → AI: add your free OpenRouter key (there is a “How to create the key” tutorial) for full answers about your notes. Without a key, I answer with local searches in your notes.',
  'No editor da nota você pode anexar imagens e gravar áudio. Em notas com anexos grandes, um botão (seta em círculo) leva você direto ao fim da nota.': 'In the note editor you can attach images and record audio. In notes with big attachments, a button (arrow in a circle) takes you straight to the end of the note.',
  'Em Ajustes → Aparência → Idioma você escolhe entre Português, English e Español — o app inteiro e o assistente de IA passam a responder no idioma escolhido.': 'In Settings → Appearance → Language you can choose between Português, English and Español — the whole app and the AI assistant switch to the language you pick.',
  'Você ainda não tem nenhuma nota ou tarefa. Crie uma nota ou tarefa primeiro e depois me pergunte! 📝✨': 'You do not have any notes or tasks yet. Create a note or task first, then ask me! 📝✨',
  'Só posso ajudar com assuntos sobre as suas notas e tarefas ✨\n\nNão encontrei nada relacionado à sua pergunta. Configure a chave gratuita de IA em Ajustes → IA para eu conseguir responder melhor.': 'I can only help with things about your notes and tasks ✨\n\nI found nothing related to your question. Set up the free AI key in Settings → AI so I can answer better.',
  'Encontrei isso nas suas notas e tarefas:': 'Here is what I found in your notes and tasks:',
  '(modo offline — adicione a chave gratuita de IA em Ajustes → IA para respostas completas como ChatGPT)': '(offline mode — add the free AI key in Settings → AI for full ChatGPT-like answers)',
  'Não consegui conectar à IA online agora, mas encontrei isto nas suas notas e tarefas:': 'I could not reach the online AI right now, but I found this in your notes and tasks:',
  '(Verifique sua internet ou a chave de IA em Ajustes.)': '(Check your internet or the AI key in Settings.)',
  'Não consegui conectar à IA online agora. Verifique sua internet ou a chave de IA em Ajustes → IA e tente de novo.': 'I could not reach the online AI right now. Check your internet or the AI key in Settings → AI and try again.',
  'A chave de IA configurada não é válida. Verifique em Ajustes → IA.': 'The AI key you entered is not valid. Check it in Settings → AI.',
  'A IA gratuita está com limite de uso no momento. Aguarde um minuto e tente de novo.': 'The free AI is rate-limited right now. Wait a minute and try again.',
  'A IA gratuita está com limite de uso no momento (muitas perguntas em pouco tempo). Aguarde um minuto e tente de novo — ou pergunte em Ajustes → IA se a chave está certa.': 'The free AI is rate-limited right now (too many questions in a short time). Wait a minute and try again — or check in Settings → AI whether the key is correct.',
  'Abra uma nota para eu resumir. ✍️': 'Open a note so I can summarize it. ✍️',
  'Para resumir com IA, configure sua chave gratuita em Ajustes → IA. 🔑': 'To summarize with AI, set up your free key in Settings → AI. 🔑',
  'Resuma esta nota:': 'Summarize this note:',
  'Sem título': 'Untitled',
  concluída: 'done',
  pendente: 'pending',
  'recorrência': 'recurrence',
  'horário': 'time',
  Tarefa: 'Task',
  'Tarefas:': 'Tasks:',
  'sem conteúdo': 'no content',
  // --- Editor / IA (chrome) ---
  'Desculpe, não consegui responder agora. Tente de novo.': 'Sorry, I could not answer right now. Try again.',
  'Não consegui gerar o resumo agora. Tente de novo.': 'I could not generate the summary right now. Try again.',
  Configurações: 'Settings',
  Aparência: 'Appearance',
  'Modo Escuro': 'Dark Mode',
  Idioma: 'Language',
  'Idioma do aplicativo e do assistente de IA': 'App and AI assistant language',
  'Escolha o idioma do aplicativo e do assistente de IA': 'Choose the language for the app and the AI assistant',
  'Português (padrão)': 'Portuguese (default)',
  Inglês: 'English',
  Espanhol: 'Spanish',
  Interface: 'Interface',
  'Ajuda no Menu +': 'Help in the + menu',
  'Mostrar botão de guia no menu de criação': 'Show a guide button in the create menu',
  Alarme: 'Alarm',
  'Som do alarme': 'Alarm sound',
  'Toca no volume de alarme, no máximo': 'Plays at the alarm volume, at maximum',
  'Soneca do alarme': 'Alarm snooze',
  'Tempo ao tocar em “Daqui a X min”': 'Delay when tapping “Snooze X min”',
  'Permissões do alarme': 'Alarm permissions',
  'Popup em tela cheia · Xiaomi · bateria': 'Full-screen popup · Xiaomi · battery',
  Anúncios: 'Ads',
  'Anúncios removidos': 'Ads removed',
  'Premium liberado por convite do desenvolvedor': 'Premium granted by a developer invite',
  'Obrigado pelo apoio! Sem anúncios para sempre': 'Thanks for your support! No ads forever',
  'Premium por convite': 'Premium by invite',
  'Remover anúncios para sempre': 'Remove ads forever',
  'Pagamento único pela Play Store': 'One-time payment via the Play Store',
  'Entre na sua conta para comprar — o Premium fica vinculado ao seu email': 'Sign in to buy — Premium is tied to your account email',
  'Para comprar o Premium, primeiro entre na sua conta Google. O Premium fica vinculado ao email da conta que fez a compra.': 'To buy Premium, first sign in to your Google account. Premium is linked to the email of the account that made the purchase.',
  'Premium comprado · vinculado a {email}': 'Premium purchased · linked to {email}',
  'Este aparelho já tem Premium comprado pelo email {email}. Entre com essa conta para usar sem anúncios.': 'This device already has Premium purchased by {email}. Sign in with that account to go ad-free.',
  Entrar: 'Sign in',
  'Pagamento indisponível neste aparelho.': 'Payment is not available on this device.',
  'Este aparelho já tem Premium comprado. Entre com a conta que fez a compra para usar sem anúncios.': 'This device already has Premium purchased. Sign in with the account that bought it to go ad-free.',
  IA: 'AI',
  'Chave da IA (gratuita)': 'AI key (free)',
  'Respostas como ChatGPT usando modelos grátis do OpenRouter': 'Answers like ChatGPT using free OpenRouter models',
  'Como criar a chave': 'How to create the key',
  'Abrir site': 'Open site',
  'tutorial.chave.passo1': 'Tap “Open site” below — it opens your browser at openrouter.ai',
  'tutorial.chave.passo2': 'Tap “Continue with Google” and sign in with your account (the same one used in the app)',
  'tutorial.chave.passo3': 'On the keys page, tap “+ Create Key” (keep “Free models” checked) and confirm',
  'tutorial.chave.passo4': 'The site shows your key (it starts with sk-or-v1-). Press and hold it → Copy',
  'tutorial.chave.passo5': 'Return to the app and paste it into the field above — hold your finger on the field and tap “Paste”',
  'Entendi!': 'Got it!',
  'Versão do App': 'App version',
  Segurança: 'Security',
  'Bloquear App': 'Lock App',
  'Exigir biometria ao abrir o aplicativo': 'Require biometrics when opening the app',
  'Tempo de Bloqueio': 'Lock timeout',
  'Janela de carência antes de bloquear': 'Grace period before locking',
  Imediato: 'Immediate',
  Erro: 'Error',
  'Este dispositivo não possui suporte a biometria.': 'This device does not support biometrics.',
  'Nenhuma biometria (digital ou rosto) cadastrada no sistema.': 'No biometrics (fingerprint or face) enrolled on this device.',
  'Confirme sua identidade para ativar': 'Confirm your identity to enable',
  'Tempo para Bloqueio': 'Lock timeout',
  'Após quanto tempo fora do app devemos exigir a biometria?': 'After how long away from the app should we require biometrics?',
  Imediatamente: 'Immediately',
  '{n} minutos': '{n} minutes',
  '{n} min': '{n} min',
  'Quanto tempo o alarme adia ao tocar em "Daqui a X min"?': 'How long should the alarm snooze when you tap “Snooze X min”?',
  'Toca no volume de alarme do celular, forçado ao máximo': 'Plays at the phone alarm volume, forced to maximum',
  Clássico: 'Classic',
  Digital: 'Digital',
  Suave: 'Gentle',
  Urgente: 'Urgent',
  Eco: 'Echo',
  Ondas: 'Waves',
  'Bipes de despertador tradicionais': 'Traditional alarm beeps',
  'Toque de telefone digital': 'Digital phone ringtone',
  'Arpejo calmo para acordar devagar': 'Calm arpeggio to wake up slowly',
  'Bipes rápidos e fortes': 'Fast, loud beeps',
  'Melodia de cuco com eco': 'Cuckoo melody with echo',
  'Mar calmo batendo na areia': 'Calm sea washing onto the sand',
  'Criar sua chave grátis': 'Create your free key',
  'Leva 1 minuto e não pede cartão': 'Takes 1 minute and asks for no card',
  Negrito: 'Bold',
  Itálico: 'Italic',
  Sublinhado: 'Underline',
  Tachado: 'Strikethrough',
  'Lista com marcadores': 'Bulleted list',
  'Lista numerada': 'Numbered list',
  'Gravar áudio': 'Record audio',
  'Parar gravação': 'Stop recording',
  'Inserir imagem': 'Insert image',
  // --- Aba / rodapé ---
  Notas: 'Notes',
  Tarefas: 'Tasks',
  Ajustes: 'Settings',
  // --- Home / seleção / pastas ---
  Cancelar: 'Cancel',
  Excluir: 'Delete',
  'Excluir itens': 'Delete items',
  Criar: 'Create',
  'Criar pasta': 'Create folder',
  'Criar nova pasta...': 'Create new folder...',
  'Nova pasta': 'New folder',
  Pasta: 'Folder',
  'Nome da pasta': 'Folder name',
  'Mover para pasta': 'Move to folder',
  'Renomear pasta': 'Rename folder',
  Salvar: 'Save',
  Sucesso: 'Success',
  'Excluir pasta': 'Delete folder',
  'Apagar {n} item selecionado?': 'Delete {n} selected item?',
  'Apagar {n} itens selecionados?': 'Delete {n} selected items?',
  'Leva os {n} para dentro': 'Move the {n} in',
  'item selecionado': 'item selected',
  'itens selecionados': 'items selected',
  '{n} selecionada': '{n} selected',
  '{n} selecionadas': '{n} selected',
  'Deseja apagar esta nota?': 'Delete this note?',
  'Deseja apagar esta lista?': 'Delete this list?',
  'Nota sem título': 'Untitled note',
  'Lista sem título': 'Untitled list',
  'sem título': 'untitled',
  'Toque para editar...': 'Tap to edit...',
  'Nenhuma nota encontrada': 'No notes found',
  'Procurar em suas notas...': 'Search your notes...',
  'Comece a organizar suas ideias': 'Start organizing your ideas',
  'Comece a escrever...': 'Start writing...',
  'Usar senha': 'Use password',
  'Nada foi gravado.': 'Nothing was recorded.',
  'Mover áudio': 'Move audio',
  'Armazenamento no Drive': 'Drive storage',
  'Dados do app na nuvem': 'App data in the cloud',
  'Não foi possível conectar ao armazenamento do Drive.': 'Could not connect to Drive storage.',
  'Tentar novamente': 'Try again',
  'Mostrando dados anteriores. Toque para atualizar.': 'Showing previous data. Tap to refresh.',
  'Não foi possível atualizar. Toque para tentar de novo.': 'Could not refresh. Tap to try again.',
  'Armazenamento quase cheio ({pct}%) — libere espaço para o app continuar fazendo backup.': 'Storage almost full ({pct}%) — free up space so the app can keep backing up.',
  'sem limite': 'no limit',
  'Conta com armazenamento ilimitado do Drive.': 'This account has unlimited Drive storage.',
  '{n} GB': '{n} GB',
  '{n} MB': '{n} MB',
  '{n} KB': '{n} KB',
  'item salvo': 'item saved',
  'itens salvos': 'items saved',
  '{n} itens salvos': '{n} items saved',
  '{n} itens na lista': '{n} items in the list',
  'Toque no + para criar sua primeira nota': 'Tap + to create your first note',
  'Nenhuma pasta ainda — crie a primeira!': 'No folders yet — create your first one!',
  'Organize suas notas e listas em pastas': 'Organize your notes and lists in folders',
  'Guia Rápido': 'Quick guide',
  'Arraste para a': 'Swipe to the',
  Direita: 'right',
  Esquerda: 'left',
  'para fixar itens no topo': 'to pin items to the top',
  'para excluir uma nota': 'to delete a note',
  'Suas notas são salvas': 'Your notes are saved',
  automaticamente: 'automatically',
  'na sua conta Google': 'to your Google account',
  'Conectado como {nome}': 'Signed in as {nome}',
  'Conectado como {nome}. {quantidade} itens criados deslogado foram transferidos para sua conta.': 'Signed in as {nome}. {quantidade} items created while signed out were transferred to your account.',
  'Apagar backups da nuvem': 'Delete cloud backups',
  'Apagar todos os dados': 'Erase all data',
  'Isso exclui PERMANENTEMENTE do aparelho todas as notas, listas, pastas, tarefas e lembretes — e também o backup na nuvem da conta logada. NÃO dá para desfazer.': 'This PERMANENTLY erases all notes, lists, folders, tasks and reminders from this device — and also the signed-in account\'s cloud backup. This CANNOT be undone.',
  'Digite para confirmar': 'Type to confirm',
  'Digite APAGAR para confirmar a exclusão de todos os dados.': 'Type DELETE to confirm erasing all data.',
  APAGAR: 'DELETE',
  'Apagando...': 'Erasing...',
  'Todos os dados foram apagados.': 'All data has been erased.',
  'Não foi possível apagar tudo. Tente novamente.': 'Could not erase everything. Try again.',
  Continuar: 'Continue',
  'Apagar backups': 'Delete backups',
  'Isso vai excluir PERMANENTEMENTE o backup na nuvem desta conta. As notas no aparelho não serão afetadas. Deseja continuar?': 'This will PERMANENTLY delete the cloud backup of this account. Notes on this device will not be affected. Continue?',
  'Apagar tudo': 'Delete all',
  'Backups apagados da nuvem.': 'Cloud backups deleted.',
  'Você precisa de internet para apagar os backups.': 'You need internet to delete the backups.',
  'Falha ao apagar os backups.': 'Failed to delete the backups.',
  Login: 'Sign in',
  'Entrar com Google': 'Sign in with Google',
  Sair: 'Log out',
  'Trocar Conta': 'Switch account',
  Usuário: 'User',
  Offline: 'Offline',
  'Sem sincronização': 'Not synced',
  'O login não foi concluído.': 'Sign-in was not completed.',
  'Login não concluído. Tente novamente.': 'Sign-in not completed. Try again.',
  'Falha no login': 'Sign-in failed',
  'Deseja realmente desconectar?': 'Do you really want to sign out?',
  'Você está offline. Conecte-se à internet para trocar de conta.': 'You are offline. Connect to the internet to switch accounts.',
  'Você precisa de internet para restaurar.': 'You need internet to restore.',
  'Dados restaurados!': 'Data restored!',
  'Falha ao restaurar.': 'Could not restore.',
  'Desconectado.': 'Signed out.',
  // --- Editor (chrome + lembretes) ---
  'Gravando...': 'Recording...',
  Pronto: 'Done',
  Editar: 'Edit',
  Título: 'Title',
  'Lembrete de revisão': 'Review reminder',
  'Me lembre de ver esta nota': 'Remind me to review this note',
  'A cada X dias': 'Every X days',
  'Dias da semana': 'Days of the week',
  Horário: 'Time',
  Data: 'Date',
  Escolher: 'Choose',
  Remover: 'Remove',
  'Falta o dia': 'Missing the date',
  'Escolha a data do lembrete.': 'Choose the reminder date.',
  'Faltam os dias': 'Missing the days',
  'Escolha pelo menos um dia da semana.': 'Pick at least one day of the week.',
  'Horário no passado': 'Time already passed',
  'Escolha uma data e horário futuros para o lembrete.': 'Pick a future date and time for the reminder.',
  'Permissão negada.': 'Permission denied.',
  'Permissão necessária.': 'Permission needed.',
  'Não foi possível iniciar a gravação.': 'Could not start recording.',
  'Falha ao salvar o áudio.': 'Could not save the audio.',
  'Não foi possível carregar a imagem.': 'Could not load the image.',
  'Notificações desativadas': 'Notifications disabled',
  'Permita as notificações nas configurações do aparelho para receber os lembretes das tarefas.': 'Allow notifications in the device settings to receive task reminders.',
  'Confirme para remover a proteção desta nota': 'Confirm to remove the protection from this note',
  // --- Editor: modal da IA ---
  'NotaIA': 'NotaIA',
  'Pergunte sobre suas notas': 'Ask about your notes',
  Perguntar: 'Ask',
  Resumo: 'Summary',
  'Pergunte sobre suas notas...': 'Ask about your notes...',
  'A conversa com IA precisa de chave': 'The AI chat requires a key',
  'Adicione sua chave gratuita em\nAjustes → IA para conversar com a IA de verdade.': 'Add your free key in\nSettings → AI to chat with the real AI.',
  'Ir para Ajustes': 'Go to Settings',
  'Pergunte qualquer coisa sobre suas notas. ✨\nEx.: «Quanto custa o arroz?» ou «Qual a data da festa?»': 'Ask anything about your notes. ✨\nE.g.: «How much is the rice?» or «What is the party date?»',
  'Resumindo…': 'Summarizing…',
  'Gerar resumo com IA': 'Generate AI summary',
  'Lembrete em {data} às {hora}': 'Reminder on {data} at {hora}',
  'Revisar a cada {n} dias às {hora}': 'Review every {n} days at {hora}',
  'Revisar às {hora}': 'Review at {hora}',
  'Revisar às {dias}, às {hora}': 'Review on {dias} at {hora}',
  // --- Editor de listas ---
  LISTA: 'LIST',
  'Título da lista': 'List title',
  'Adicionar item...': 'Add item...',
  'Progresso da lista': 'List progress',
  'Toque em um item para marcar como feito': 'Tap an item to mark it as done',
  'Sua lista está vazia': 'Your list is empty',
  'Adicione o primeiro item acima para começar.': 'Add your first item above to get started.',
  'Concluído': 'Done',
  Pendente: 'Pending',
  'Nova Lista': 'New List',
  // --- Aba de tarefas ---
  'Um passo de cada vez': 'One step at a time',
  'O que precisa ser feito?': 'What needs to be done?',
  'CONCLUÍDAS': 'DONE',
  'Tudo limpo por aqui!': 'All clear here!',
  'Adicione sua primeira tarefa acima.': 'Add your first task above.',
  'Uma vez': 'Once',
  Diária: 'Daily',
  Domingo: 'Sunday',
  Segunda: 'Monday',
  Terça: 'Tuesday',
  Quarta: 'Wednesday',
  Quinta: 'Thursday',
  Sexta: 'Friday',
  Sábado: 'Saturday',
  'Vou fazer': "I'll do it",
  'Deixar para depois': 'Remind me later',
  'Está na hora de revisar esta nota!': 'Time to review this note!',
  'Está na hora de fazer isso!': 'Time to do it!',
  'Daqui a {n} min': 'In {n} min',
  'Está na hora de: {titulo}': 'Time to: {titulo}',
  'Lembrete: {titulo}': 'Reminder: {titulo}',
  'Está na hora de revisar esta nota': 'Time to review this note',
  'Revisado': 'Reviewed',
  // --- Pasta (tela interna) ---
  'Pasta vazia': 'Empty folder',
  'Toque no + para criar uma nota ou lista aqui dentro': 'Tap + to create a note or list here',
  NOTAS: 'NOTES',
  LISTAS: 'LISTS',
  'Nenhum resultado': 'No results',
  'Nenhum item encontrado para &quot;{busca}&quot;': 'No items found for &quot;{busca}&quot;',
  Fixar: 'Pin',
  'Dê um novo nome para esta pasta': 'Give this folder a new name',
  '{n} item na pasta': '{n} item in the folder',
  '{n} itens na pasta': '{n} items in the folder',
  'Procurar nesta pasta...': 'Search in this folder...',
  'Excluir a pasta &quot;{nome}&quot;? As notas e listas dela voltam para a lista principal.': 'Delete the folder &quot;{nome}&quot;? Its notes and lists go back to the main list.',
  'Apagar a nota &quot;{titulo}&quot;?': 'Delete the note &quot;{titulo}&quot;?',
  'Apagar a lista &quot;{titulo}&quot;?': 'Delete the list &quot;{titulo}&quot;?',
  'Apagar {n} {qtd} selecionado{s}?': 'Delete {n} {qtd} selected{s}?',
  // --- Feedback ---
  'Como está usando o app?': 'How are you using the app?',
  'Seu feedback ajuda a melhorar o Simple Notes. Leva menos de um minuto!': 'Your feedback helps improve Simple Notes. It takes less than a minute!',
  'Avaliar no Google Play': 'Rate on Google Play',
  'Enviar feedback por e-mail': 'Send feedback by email',
  'Agora não': 'Not now',
  'Feedback — Simple Notes': 'Feedback — Simple Notes',
  'App Bloqueado': 'App Locked',
  'Desbloquear': 'Unlock',
  'Toque no botão abaixo para acessar suas notas, tarefas e anotações.': 'Tap the button below to access your notes, tasks and annotations.',
  'Bloqueio automático: imediato ao sair do app': 'Auto-lock: immediate when leaving the app',
  'Bloqueio automático: após {n} min fora do app': 'Auto-lock: after {n} min away from the app',
  'Acesse suas informações': 'Access your information',
  'Usar senha do dispositivo': 'Use device password',
  'Verificando permissões...': 'Checking permissions...',
  'Abrir': 'Open',
  'Notificações ativadas': 'Notifications enabled',
  'O app pode tocar o som do alarme': 'The app can play the alarm sound',
  'O app precisa da permissão para tocar o alarme': 'The app needs permission to play the alarm',
  'Alarme exato': 'Exact alarm',
  'O alarme dispara na hora certa': 'The alarm goes off on time',
  'Sem isso, o alarme pode atrasar alguns minutos': 'Without this, the alarm may be a few minutes late',
  'Exibir pop-ups em segundo plano (MIUI)': 'Show pop-ups in the background (MIUI)',
  'Popup liberado para abrir fora do app': 'Popup allowed to open outside the app',
  'Essencial no Xiaomi para o alarme abrir como popup (não só notificação)': 'Essential on Xiaomi for the alarm to open as a popup (not just a notification)',
  'Popup sobre outros apps': 'Popup over other apps',
  'O alarme abre por cima de tudo, mesmo com a tela ligada': 'The alarm opens above everything, even with the screen on',
  'Permite o alarme abrir por cima de outros apps': 'Allows the alarm to open over other apps',
  'Tela cheia (Android 14+)': 'Full screen (Android 14+)',
  'Pode abrir por cima de tudo, mesmo bloqueado': 'Can open above everything, even when locked',
  'Ative em Ajustes → Acesso especial → Tela cheia': 'Enable in Settings → Special access → Full screen',
  'Otimização de bateria': 'Battery optimization',
  'Sem restrições — alarme toca com o app fechado': 'Unrestricted — alarm rings with the app closed',
  'Defina "Sem restrições" para o alarme tocar com o app fechado': 'Set "Unrestricted" for the alarm to ring with the app closed',
  'Iniciar automaticamente (Autostart)': 'Start automatically (Autostart)',
  'Garante que o alarme dispare com o app fechado': 'Ensures the alarm fires with the app closed',
  'Ajustes → Apps → Gerenciar apps → Simple Notes → Iniciar automaticamente': 'Settings → Apps → Manage apps → Simple Notes → Start automatically',
  'Notificações na tela de bloqueio': 'Notifications on the lock screen',
  'Mostra o alarme com o celular bloqueado': 'Shows the alarm with the phone locked',
  'Ajustes → Notificações → Na tela de bloqueio → Mostrar tudo': 'Settings → Notifications → On the lock screen → Show all',
  'No Android, o alarme só abre em POPUP (por cima de outros apps) se o app tiver as permissões abaixo. Em aparelhos Xiaomi (MIUI/HyperOS) são necessários alguns passos extras.': 'On Android, the alarm only opens as a POPUP (over other apps) if the app has the permissions below. On Xiaomi devices (MIUI/HyperOS) some extra steps are needed.',
  'Com a permissão de popup (sobreposição) ativada, o alarme abre por cima de tudo — mesmo com a tela ligada. Sem ela: com a tela bloqueada/desligada abre em tela cheia; com a tela ligada mostra apenas um aviso no topo (toque nele para abrir o alarme).': 'With the popup (overlay) permission enabled, the alarm opens above everything — even with the screen on. Without it: with the screen locked/off it opens full screen; with the screen on it only shows a banner at the top (tap it to open the alarm).',
  'Dispositivo Xiaomi / MIUI detectado — ative os itens abaixo para o popup funcionar': 'Xiaomi / MIUI device detected — enable the items below for the popup to work',
  'Dica: se ainda assim o popup não abrir, verifique também em Ajustes → Bateria → Gerenciar bateria do aparelho se o app está como “Sem restrições” (o nome varia por fabricante: Samsung, Xiaomi, Motorola, etc.).': 'Tip: if the popup still does not open, also check in Settings → Battery → Manage battery whether the app is set to "Unrestricted" (the name varies by manufacturer: Samsung, Xiaomi, Motorola, etc.).',
  'Apagar': 'Delete',
  'Apagar áudio': 'Delete audio',
  'Deseja remover este áudio da nota?': 'Do you want to remove this audio from the note?',
  'Gravação de áudio': 'Audio recording',
  'Pausar áudio': 'Pause audio',
  'Reproduzir áudio': 'Play audio',
  '“Tela cheia” do Android 14+': '“Full screen” from Android 14+',
  '“Exibir pop-ups em segundo plano” do MIUI': '“Show pop-ups in the background” from MIUI',
  '“Exibir sobre outros apps”': '“Display over other apps”',
  'Popup do alarme bloqueado': 'Alarm popup blocked',
  'Para o alarme abrir em POPUP (por cima de outros apps, mesmo com o celular bloqueado), ative: {itens}.': 'For the alarm to open as a POPUP (over other apps, even with the phone locked), enable: {itens}.',
  ' No Xiaomi, ative também “Iniciar automaticamente” e “Sem restrições” na bateria.': ' On Xiaomi, also enable “Start automatically” and “Unrestricted” in battery.',
  'Abrir permissões': 'Open permissions',
  // --- DESKTOP (interface do PC) ---
  'Todas': 'All',
  'Fixadas': 'Pinned',
  'NAVEGAR': 'BROWSE',
  'PASTAS': 'FOLDERS',
  '+ Nova': '+ New',
  'Desconectado': 'Disconnected',
  'Faça login para vincular ao celular': 'Sign in to link with your phone',
  'Local apenas': 'Local only',
  'Conectar Google': 'Connect Google',
  'Sincronizar': 'Sync',
  'Buscar…': 'Search…',
  '0 itens': '0 items',
  'Nova nota': 'New note',
  '+ Lista': '+ List',
  '0 selecionados': '0 selected',
  'Clique nos cards para selecionar': 'Click cards to select',
  'Selecionar todos': 'Select all',
  'Mover…': 'Move…',
  'nova nota': 'new note',
  'buscar': 'search',
  'fechar editor': 'close editor',
  'clique para selecionar': 'click to select',
  'Adicionar': 'Add',
  'Assistente IA': 'AI Assistant',
  'Converse sobre suas notas': 'Chat about your notes',
  'Dica: a IA usa suas notas e tarefas como contexto. Sem internet, faz busca local.': 'Tip: the AI uses your notes and tasks as context. Offline, it searches locally.',
  'Pergunte sobre suas notas…': 'Ask about your notes…',
  'Enviar': 'Send',
  'Ajustes do app no PC': 'App settings on PC',
  'Tema escuro': 'Dark theme',
  'OLED no PC, igual ao celular': 'OLED on PC, same as phone',
  'App e assistente de IA': 'App and AI assistant',
  'Vincular com o celular': 'Link with your phone',
  'Faça login com a mesma conta do celular': 'Sign in with the same account as your phone',
  'Sincronização Drive': 'Drive sync',
  'Sincronizar agora': 'Sync now',
  'Inteligência Artificial': 'Artificial Intelligence',
  'Chave da IA (OpenRouter)': 'AI key (OpenRouter)',
  'Respostas como ChatGPT com modelos grátis': 'ChatGPT-like answers with free models',
  'Bloquear app': 'Lock app',
  'PIN de 4 dígitos ao abrir o aplicativo': '4-digit PIN when opening the app',
  'PIN': 'PIN',
  'Nenhum PIN definido': 'No PIN set',
  'Definir PIN': 'Set PIN',
  'Tempo para bloquear': 'Lock timeout',
  'Janela antes de pedir o PIN': 'Window before asking for the PIN',
  'Soneca': 'Snooze',
  'Tempo do "Daqui a X min"': 'Time for "In X min"',
  'Usado na notificação do PC': 'Used in the PC notification',
  'Dados': 'Data',
  'Apagar tudo?': 'Delete everything?',
  'Digite APAGAR para confirmar:': 'Type DELETE to confirm:',
  'Apagar TUDO': 'Delete ALL',
  'Digite o nome da pasta': 'Type the folder name',
  'Renomear': 'Rename',
  'Mover itens': 'Move items',
  'Mover': 'Move',
  'Defina o PIN': 'Set the PIN',
  '4 dígitos numéricos': '4 numeric digits',
  'Limpar': 'Clear',
  'App bloqueado': 'App locked',
  'Digite o PIN de 4 dígitos — clique ou use o teclado': 'Type the 4-digit PIN — click or use the keyboard',
  'Lembrete': 'Reminder',
  'Inserir áudio': 'Insert audio',
  'Escreva sua nota…': 'Write your note…',
  'Progresso': 'Progress',
  'Clique no quadrado para marcar como feito · arraste ⋮ para reordenar': 'Click the square to mark as done · drag ⋮ to reorder',
  'Adicionar item… (Enter)': 'Add item… (Enter)',
  'Fechar': 'Close',
  'Minimizar': 'Minimize',
  'Maximizar': 'Maximize',
  'Fechar janela': 'Close window',
  'Sincronizar com o Drive': 'Sync with Drive',
  'Sincronizando · {n} anexo(s) pendente(s)': 'Syncing · {n} attachment(s) pending',
  'Sincronizando…': 'Syncing…',
  'Falha ao sincronizar — tentando de novo': 'Sync failed — retrying',
  // --- IA: proposta de edição (confirmação antes de aplicar) ---
  'Quero editar esta nota': 'I want to edit this note',
  'Título novo:': 'New title:',
  'Aplicar edição': 'Apply edit',
  'Aplicando…': 'Applying…',
  '✅ Edição aplicada na nota.': '✅ Edit applied to the note.',
  'Não permitir': 'Do not allow',
  'Permitir': 'Allow',
  'Aplicar este texto na nota?': 'Apply this text to the note?',
  '✅ Conteúdo aplicado na nota.': '✅ Content applied to the note.',
  'Cancelar alteração da IA': 'Undo the AI change',
  '↩️ Alteração cancelada — a nota voltou ao que era.': '↩️ Change cancelled — the note is back to how it was.',
  // --- Desktop: sistema (auto-start + bandeja) ---
  'Sistema': 'System',
  'Iniciar com o Windows': 'Start with Windows',
  'Abre sozinho ao ligar o PC — fica na bandeja e os alarmes tocam mesmo em segundo plano': 'Starts automatically when the PC boots — stays in the tray and alarms ring even in the background',
  'Minimizar para a bandeja': 'Minimize to tray',
  'Fechar só esconde a janela — alarmes continuam tocando; saia de verdade pelo ícone da bandeja': 'Closing only hides the window — alarms keep ringing; quit for real from the tray icon',
  'Sempre ativo': 'Always on',
  // --- Desktop: textos de interface (renderizadores JS) ---
  'A IA não devolveu a edição pronta. Abra a nota que deseja alterar e peça de novo.': 'The AI did not return the ready edit. Open the note you want to change and ask again.',
  'Alterar PIN': 'Change PIN',
  'Alteração cancelada — voltou ao que era.': 'Change cancelled — back to how it was.',
  'Alteração da IA cancelada': 'AI change cancelled',
  'Apagado localmente (nuvem falhou)': 'Deleted locally (cloud failed)',
  'Apagar TUDO deste PC (local apenas). Digite APAGAR para confirmar.': 'Delete EVERYTHING from this PC (local only). Type APAGAR to confirm.',
  'Apagar TUDO deste PC? Digite APAGAR para confirmar.': 'Delete EVERYTHING from this PC? Type APAGAR to confirm.',
  'Apagar TUDO do PC e da nuvem': 'Delete EVERYTHING from the PC and the cloud',
  'Ações em lote': 'Batch actions',
  'Concluída': 'Completed',
  'Conectado! Sincronizando…': 'Connected! Syncing…',
  'Configure o client_secret.txt e faça login': 'Set up client_secret.txt and sign in',
  'Crie sua primeira nota — ela aparece no celular após sincronizar.': 'Create your first note — it shows up on your phone after syncing.',
  'Desbloqueado': 'Unlocked',
  'Desfixados': 'Unpinned',
  'Digite APAGAR para confirmar': 'Type APAGAR to confirm',
  'Digite novamente': 'Type again',
  'Digite o nome da nova pasta': 'Type the new folder name',
  'Digite o título da tarefa': 'Type the task title',
  'Digite um nome': 'Type a name',
  'Edição aplicada.': 'Edit applied.',
  'Excluir tarefa': 'Delete task',
  'Excluído': 'Deleted',
  'Falha ao apagar': 'Failed to delete',
  'Falha ao enviar — tentando de novo': 'Upload failed — retrying',
  'Falha ao sincronizar': 'Sync failed',
  'Fixada': 'Pinned',
  'Gerenciar pasta': 'Manage folder',
  'IA não carregada': 'AI not loaded',
  'Item adicionado': 'Item added',
  'Item não encontrado': 'Item not found',
  'Lista': 'List',
  'Nenhum backup no Drive — este PC vira a fonte': 'No backup on Drive — this PC becomes the source',
  'No celular: Ajustes → IA → Como criar a chave (tutorial). No PC: mesma chave do OpenRouter': 'On the phone: Settings → AI → How to create the key (tutorial). On the PC: the same OpenRouter key',
  'Nota criada': 'Note created',
  'Notas voltam para Todas.': 'Notes go back to All.',
  'Notas, listas e tarefas serão perdidas. Digite APAGAR para confirmar.': 'Notes, lists and tasks will be lost. Type APAGAR to confirm.',
  'Notificação + som disparados': 'Notification + sound triggered',
  'Nova lista': 'New list',
  'Novo PIN': 'New PIN',
  'Novo item': 'New item',
  'Não consegui alterar.': 'I could not apply the change.',
  'Não encontrei a nota/lista que a IA indicou para editar.': 'I could not find the note/list the AI pointed to.',
  'Não vai mais iniciar com o Windows': 'It will no longer start with Windows',
  'PIN definido (4 dígitos) — toque para alterar': 'PIN set (4 digits) — click to change',
  'PINs não conferem': 'PINs do not match',
  'Para alterar — use teclado ou clique': 'To change — use the keyboard or click',
  'Pasta criada': 'Folder created',
  'Pasta excluída': 'Folder deleted',
  'Pasta renomeada': 'Folder renamed',
  'Quer editar esta lista': 'Edit this list?',
  'Quer editar esta nota': 'Edit this note?',
  'Renomeie a pasta ou exclua (notas voltam para Todas)': 'Rename the folder or delete it (notes go back to All)',
  'Salvar nome': 'Save name',
  'Salvo · sincronizando…': 'Saved · syncing…',
  'Selecione a pasta de destino': 'Select the destination folder',
  'Sincronizado com o Drive': 'Synced with Drive',
  'Sincronizado com o celular': 'Synced with your phone',
  'Tarefa criada · alarme agendado': 'Task created · alarm scheduled',
  'Tarefa excluída': 'Task deleted',
  'Tema claro': 'Light theme',
  'Texto aplicado na nota.': 'Text applied to the note.',
  'Vai iniciar com o Windows': 'It will start with Windows',
  'Adicione sua primeira tarefa acima — o alarme toca no horário mesmo com o app minimizado.': 'Add your first task above — the alarm rings on time even with the app minimized.',
  'Sem pasta (Todas)': 'No folder (All)',
  'Mover {n} item(ns) para:': 'Move {n} item(s) to:',
  'Apagar {n} item(ns)? Esta ação não pode ser desfeita.': 'Delete {n} item(s)? This cannot be undone.',
  'Apagar {n} item(ns) selecionado(s)?': 'Delete {n} selected item(s)?',
  'Excluir pasta "{nome}"? Notas voltam para Todas.': 'Delete folder "{nome}"? Notes go back to All.',
  'Excluir tarefa "{nome}"?': 'Delete task "{nome}"?',
  'Excluir "{nome}"?': 'Delete "{nome}"?',
  'Áudio inserido': 'Audio inserted',
  'Anexo salvo — enviando para o Drive': 'Attachment saved — uploading to Drive',
  // --- App de DESKTOP (PC) ---
  'Imagem inserida': 'Image inserted',
  'Tente outro termo.': 'Try another term.',
  '★ Fixada': '★ Pinned',
  '☆ Fixar': '☆ Pin',
  '· Fixada': '· Pinned',
  'Apagados': 'Deleted',
  'Fixados': 'Pinned',
  'Excluir?': 'Delete?',
  '4 dígitos numéricos — clique ou digite': '4 numeric digits — click or type',
  'Digite o PIN atual': 'Enter the current PIN',
  'Confirme o PIN': 'Confirm the PIN',
  'PIN salvo': 'PIN saved',
  'PIN incorreto': 'Incorrect PIN',
  '4 dígitos': '4 digits',
  'Idioma:': 'Language:',
  'Não consegui alterar': 'Could not change it',
  'Chave salva': 'Key saved',
  'Chave removida': 'Key removed',
  'Movidos': 'Moved',
  'Apagando…': 'Deleting…',
  'Tudo apagado': 'Everything deleted',
  'Abrindo navegador…': 'Opening browser…',
  'Login cancelado': 'Login cancelled',
  'Pensando…': 'Thinking…',
  'Erro:': 'Error:',
  '✅ Edição aplicada.': '✅ Edit applied.',
  '↩️ Alteração cancelada — voltou ao que era.': '↩️ Change cancelled — reverted to how it was.',
  '✅ Texto aplicado na nota.': '✅ Text applied to the note.',
  'IA editou:': 'AI edited:',
  'Soneca:': 'Snooze:',
  'URI copiado:': 'URI copied:',
  'Nenhuma pasta': 'No folders',
  '🎙 áudio': '🎙 audio',
  '🖼 imagem': '🖼 image',
  'Protegida': 'Protected',
  'Nota': 'Note',
  'Sua lista está vazia — adicione o primeiro item acima.': 'Your list is empty — add the first item above.',
  'Erro: preload não carregou.': 'Error: preload did not load.',
  '↩️ Cancelar alteração da IA': '↩️ Undo AI change',
  'Sincronizado com o Drive · {hora}': 'Synced with Drive · {hora}',
  'Aplicar este texto na nota: {titulo}': 'Apply this text to the note: {titulo}',
  'Quer editar esta lista: {titulo}': 'Edit this list: {titulo}',
  'Quer editar esta nota: {titulo}': 'Edit this note: {titulo}',
  '{n} itens · {m} pendentes': '{n} items · {m} pending',
  'Apagar TUDO do PC e da nuvem ({email})? Notas, listas e tarefas serão perdidas. Digite APAGAR para confirmar.': 'Delete EVERYTHING from the PC and the cloud ({email})? Notes, lists and tasks will be lost. Type APAGAR to confirm.',
  'Testar alarme': 'Test alarm',
  '{n} itens': '{n} items',
  '{n} tarefas': '{n} tasks',
  'Arraste': 'Drag',
  // --- IA do desktop (FAQ local + fallbacks offline) ---
  'Em Ajustes → Anúncios há "Remover anúncios para sempre" (pagamento único na Play Store). Também existe Premium por convite.': 'In Settings → Ads there is "Remove ads forever" (one-time payment on the Play Store). There is also Premium by invite.',
  'Sim! Em Ajustes → Aparência você alterna o Modo Escuro (OLED no PC, igual ao celular).': 'Yes! In Settings → Appearance you toggle Dark Mode (OLED on PC, same as the phone).',
  'Em Ajustes → Alarme você escolhe o som e a soneca (5 a 60 min). No PC o alarme toca com som do sistema + Web Audio e botão Soneca.': 'In Settings → Alarm you pick the sound and the snooze (5 to 60 min). On PC the alarm rings with the system sound + Web Audio and a Snooze button.',
  'Em Ajustes → Segurança você define um PIN de 4 dígitos. No PC ele bloqueia ao minimizar/voltar ao app; no celular usa biometria.': 'In Settings → Security you set a 4-digit PIN. On PC it locks when you minimize/return to the app; on the phone it uses biometrics.',
  'Entrando com a mesma conta Google no celular e no PC, notas/listas/pastas/tarefas ficam no Drive (backup_notas.json em appDataFolder) e sincronizam com um clique em Sincronizar.': 'Signing in with the same Google account on the phone and the PC keeps notes/lists/folders/tasks on Drive (backup_notas.json in appDataFolder) and they sync with one click on Sync.',
  'Na aba Tarefas você cria tarefas com recorrência (uma vez/diária/dias específicos) e horário, com notificação e soneca.': 'In the Tasks tab you create tasks with recurrence (once/daily/specific days) and a time, with notification and snooze.',
  'Na barra lateral, clique em + Nova para criar pasta; clique direito na pasta para renomear/excluir; selecione notas/listas com Ctrl+clique e Mover para outra pasta.': 'In the sidebar, click + New to create a folder; right-click the folder to rename/delete; select notes/lists with Ctrl+click and Move to another folder.',
  'As listas são checklists com checkbox, marcar/desmarcar e arrastar para reordenar (⋮⋮). Também moram dentro de pastas.': 'Lists are checklists with a checkbox, check/uncheck and drag to reorder (⋮⋮). They also live inside folders.',
  'No editor da nota, o ícone de sino agenda lembretes (data/hora, a cada X dias ou dias da semana). No PC o lembrete entra como tarefa com alarme.': 'In the note editor, the bell icon schedules reminders (date/time, every X days or days of the week). On PC the reminder becomes a task with an alarm.',
  'A IA fica em Ajustes → IA: cole a chave gratuita do OpenRouter (botão Como criar a chave) para respostas como ChatGPT. Sem chave, respondo buscando nas suas notas.': 'The AI lives in Settings → AI: paste the free OpenRouter key (How to create the key button) for ChatGPT-like answers. Without a key, I answer by searching your notes.',
  'No editor você insere imagem (🖼) e áudio (🎙) — no PC arraste arquivos para dentro da nota ou use Ctrl+V. No celular as imagens vão para o Drive como anexo e são baixadas ao restaurar.': 'In the editor you insert images (🖼) and audio (🎙) — on PC drag files into the note or use Ctrl+V. On the phone images go to Drive as attachments and are downloaded on restore.',
  'Em Ajustes → Aparência → Idioma escolha Português/English/Español — o app e a IA respondem no idioma escolhido.': 'In Settings → Appearance → Language choose Português/English/Español — the app and the AI answer in the chosen language.',
  'Oi! 👋 Sou o NotaIA, seu assistente do Simple Notes. Posso ajudar com notas, listas, tarefas, pastas, lembretes, backup no Drive, modo escuro e PIN. O que quer fazer?': 'Hi! 👋 I am NotaIA, your Simple Notes assistant. I can help with notes, lists, tasks, folders, reminders, Drive backup, dark mode and PIN. What would you like to do?',
  'Sou o NotaIA, assistente do Simple Notes 🤖\nAjudo com suas notas, listas, tarefas, pastas, lembretes, backup no Drive, modo escuro e bloqueio por PIN — tudo offline ou com IA online quando há chave configurada. Me diga o que precisa!': 'I am NotaIA, the Simple Notes assistant 🤖\nI help with your notes, lists, tasks, folders, reminders, Drive backup, dark mode and PIN lock — all offline or with online AI when a key is set. Tell me what you need!',
  'Só consigo ajudar com o conteúdo das suas notas 🙂\n\nPergunte sobre o que escreveu — ex: "resuma minha nota de receita" ou "o que tenho pendente?".': 'I can only help with the content of your notes 🙂\n\nAsk about what you wrote — e.g. "summarize my recipe note" or "what do I have pending?".',
  'Encontrei isso nas suas notas:': 'I found this in your notes:',
  '_(modo offline — adicione a chave gratuita em Configurações → IA para respostas como ChatGPT)_': '_(offline mode — add the free key in Settings → AI for ChatGPT-like answers)_',
  'Chave de IA inválida. Verifique em Configurações → IA (OpenRouter).': 'Invalid AI key. Check it in Settings → AI (OpenRouter).',
  'IA em limite de uso. Aguarde um minuto e tente de novo.': 'AI rate limit reached. Wait a minute and try again.',
  'Não consegui conectar à IA online, mas encontrei:': 'I could not connect to the online AI, but I found:',
  '_(Verifique a internet ou a chave em Configurações → IA)_': '_(Check your internet or the key in Settings → AI)_',
  'Não consegui conectar à IA online. Verifique a internet ou a chave em Configurações → IA.': 'I could not connect to the online AI. Check your internet or the key in Settings → AI.',
  'Versão': 'Version',
  'Vinculado ao celular pelo mesmo backup do Drive em appDataFolder.': 'Linked to your phone via the same Drive backup in appDataFolder.',
  'Remove notas, listas, pastas e tarefas do PC e da nuvem (se logado). Igual ao celular.': 'Removes notes, lists, folders and tasks from the PC and the cloud (if signed in). Same as on the phone.',
  'PIN definido em Configurações → Segurança · Backspace apaga': 'PIN set in Settings → Security · Backspace deletes',
  'Olá! Pergunte qualquer coisa sobre suas notas. Ex: "resuma minha nota de receita" ou "o que tenho pendente?"': 'Hi! Ask anything about your notes. E.g. "summarize my recipe note" or "what do I have pending?"',
  'Mostrar/ocultar': 'Show/hide',
  'Testar notificação': 'Test notification',
  'Alternar grade/lista': 'Toggle grid/list',
  'Grade': 'Grid',
  'Ctrl + N nova nota · Ctrl + F buscar · Esc fechar editor · Ctrl + clique para selecionar': 'Ctrl + N new note · Ctrl + F search · Esc close editor · Ctrl + click to select',
};

const es: Record<string, string> = {
  // --- IA / assistente (respostas exibidas ao usuário) ---
  'Você ainda não tem nenhuma nota ou tarefa. Crie uma nota ou tarefa primeiro e depois me pergunte! 📝✨': 'Aún no tienes ninguna nota ni tarea. ¡Crea una nota o tarea primero y después pregúntame! 📝✨',
  'Esse recurso não existe no Simple Notes: o app não exporta nem compartilha notas. Ele salva tudo automaticamente na sua conta Google (Drive). ✨': 'Esa función no existe en Simple Notes: la app no exporta ni comparte notas. Guarda todo automáticamente en tu cuenta de Google (Drive). ✨',
  'Sim! Em Ajustes → Anúncios há "Remover anúncios para sempre" (pagamento único pela Play Store). Também existe o Premium liberado por convite do desenvolvedor.': '¡Sí! En Configuración → Anuncios tienes “Quitar anuncios para siempre” (pago único por Google Play). También existe el Premium otorgado por invitación del desarrollador.',
  'Sim! Em Ajustes → Aparência você alterna o Modo Escuro.': '¡Sí! En Configuración → Apariencia puedes alternar el modo oscuro.',
  'Em Ajustes → Alarme você escolhe o som do alarme, ajusta a soneca (5 a 60 min) e confere as permissões (popup em tela cheia, Xiaomi e bateria).': 'En Configuración → Alarma eliges el sonido de la alarma, ajustas la posposición (5 a 60 min) y revisas los permisos (popup a pantalla completa, Xiaomi y batería).',
  'Em Ajustes → Segurança, o app pode exigir biometria (digital ou rosto) ao abrir, com tempo de bloqueio de imediato até 30 minutos.': 'En Configuración → Seguridad, la app puede exigir biometría (huella o rostro) al abrir, con un tiempo de bloqueo desde inmediato hasta 30 minutos.',
  'Entrando com sua conta Google, notas, tarefas e a chave de IA ficam salvas no Drive com backup automático — ao trocar de aparelho, entre com a mesma conta e tudo volta.': 'Al iniciar sesión con tu cuenta de Google, las notas, tareas y la clave de IA se guardan en Drive con copia de seguridad automática; al cambiar de móvil, entra con la misma cuenta y todo vuelve.',
  'Na aba Tarefas você cria tarefas com recorrência (uma vez, diária ou em dias específicos) e horário, marca como concluída e exclui. Cada tarefa dispara uma notificação no horário.': 'En la pestaña Tareas creas tareas con repetición (una vez, diaria o en días concretos) y hora, las marcas como hechas y las eliminas. Cada tarea dispara una notificación a su hora.',
  'Na tela principal, a fileira de pastas fica acima das notas: toque no sinal de + para criar uma pasta e, para mover itens, segure uma nota ou lista até entrar no modo de seleção — aí você escolhe vários itens e toca em "mover para pasta". Você também pode renomear a pasta abrindo-a.': 'En la pantalla principal, la fila de carpetas está sobre las notas: toca el signo + para crear una carpeta y, para mover elementos, mantén pulsada una nota o lista hasta entrar en el modo de selección; ahí eliges varios elementos y tocas “mover a carpeta”. También puedes renombrar la carpeta abriéndola.',
  'As listas são checklists simples que aparecem junto das notas: crie pela tela principal, fixe as importantes, e elas também podem morar dentro de pastas (crie uma lista direto dentro da pasta).': 'Las listas son checklists sencillos que aparecen junto a las notas: créalas desde la pantalla principal, fija las importantes y también pueden vivir dentro de carpetas (crea una lista directamente dentro de la carpeta).',
  'Em cada nota, o ícone de sino agenda lembretes: em data e horário, a cada X dias ou em dias da semana. Quando toca, o alarme abre em tela cheia com som e soneca.': 'En cada nota, el icono de campana agenda recordatorios: en fecha y hora, cada X días o en días de la semana. Al sonar, la alarma se abre a pantalla completa con sonido y posposición.',
  'A IA fica em Ajustes → IA: adicione a chave gratuita do OpenRouter (há o tutorial "Como criar a chave") para respostas completas sobre suas notas. Sem chave, respondo com buscas locais nas suas notas.': 'La IA está en Configuración → IA: añade la clave gratuita de OpenRouter (hay un tutorial “Cómo crear la clave”) para respuestas completas sobre tus notas. Sin clave, respondo con búsquedas locales en tus notas.',
  'No editor da nota você pode anexar imagens e gravar áudio. Em notas com anexos grandes, um botão (seta em círculo) leva você direto ao fim da nota.': 'En el editor de la nota puedes adjuntar imágenes y grabar audio. En notas con adjuntos grandes, un botón (flecha en círculo) te lleva directo al final de la nota.',
  'Em Ajustes → Aparência → Idioma você escolhe entre Português, English e Español — o app inteiro e o assistente de IA passam a responder no idioma escolhido.': 'En Configuración → Apariencia → Idioma eliges entre Português, English y Español: toda la app y el asistente de IA pasan a responder en el idioma elegido.',
  'Só posso ajudar com assuntos sobre as suas notas e tarefas ✨\n\nNão encontrei nada relacionado à sua pergunta. Configure a chave gratuita de IA em Ajustes → IA para eu conseguir responder melhor.': 'Solo puedo ayudar con asuntos sobre tus notas y tareas ✨\n\nNo encontré nada relacionado con tu pregunta. Configura la clave gratuita de IA en Configuración → IA para que pueda responder mejor.',
  'Encontrei isso nas suas notas e tarefas:': 'Esto es lo que encontré en tus notas y tareas:',
  '(modo offline — adicione a chave gratuita de IA em Ajustes → IA para respostas completas como ChatGPT)': '(modo sin conexión: añade la clave gratuita de IA en Configuración → IA para respuestas completas como ChatGPT)',
  'Não consegui conectar à IA online agora, mas encontrei isto nas suas notas e tarefas:': 'No pude conectar con la IA en línea ahora, pero encontré esto en tus notas y tareas:',
  '(Verifique sua internet ou a chave de IA em Ajustes.)': '(Revisa tu conexión o la clave de IA en Configuración.)',
  'Não consegui conectar à IA online agora. Verifique sua internet ou a chave de IA em Ajustes → IA e tente de novo.': 'No pude conectar con la IA en línea ahora. Revisa tu conexión o la clave de IA en Configuración → IA e inténtalo de nuevo.',
  'A chave de IA configurada não é válida. Verifique em Ajustes → IA.': 'La clave de IA configurada no es válida. Revísala en Configuración → IA.',
  'A IA gratuita está com limite de uso no momento. Aguarde um minuto e tente de novo.': 'La IA gratuita tiene límite de uso ahora mismo. Espera un minuto e inténtalo de nuevo.',
  'A IA gratuita está com limite de uso no momento (muitas perguntas em pouco tempo). Aguarde um minuto e tente de novo — ou pergunte em Ajustes → IA se a chave está certa.': 'La IA gratuita tiene límite de uso ahora mismo (muchas preguntas en poco tiempo). Espera un minuto e inténtalo de nuevo, o revisa en Configuración → IA si la clave es correcta.',
  'Abra uma nota para eu resumir. ✍️': 'Abre una nota para que la resuma. ✍️',
  'Para resumir com IA, configure sua chave gratuita em Ajustes → IA. 🔑': 'Para resumir con IA, configura tu clave gratuita en Configuración → IA. 🔑',
  'Resuma esta nota:': 'Resume esta nota:',
  'Sem título': 'Sin título',
  concluída: 'completada',
  pendente: 'pendiente',
  'recorrência': 'repetición',
  'horário': 'hora',
  Tarefa: 'Tarea',
  'Tarefas:': 'Tareas:',
  'sem conteúdo': 'sin contenido',
  // --- Editor / IA (chrome) ---
  'Desculpe, não consegui responder agora. Tente de novo.': 'Lo siento, no pude responder ahora. Inténtalo de nuevo.',
  'Não consegui gerar o resumo agora. Tente de novo.': 'No pude generar el resumen ahora. Inténtalo de nuevo.',
  Configurações: 'Configuración',
  Aparência: 'Apariencia',
  'Modo Escuro': 'Modo oscuro',
  Idioma: 'Idioma',
  'Idioma do aplicativo e do assistente de IA': 'Idioma de la app y del asistente de IA',
  'Escolha o idioma do aplicativo e do assistente de IA': 'Elige el idioma de la app y del asistente de IA',
  'Português (padrão)': 'Portugués (predeterminado)',
  Inglês: 'Inglés',
  Espanhol: 'Español',
  Interface: 'Interfaz',
  'Ajuda no Menu +': 'Ayuda en el menú +',
  'Mostrar botão de guia no menu de criação': 'Mostrar un botón de guía en el menú de creación',
  Alarme: 'Alarma',
  'Som do alarme': 'Sonido de alarma',
  'Toca no volume de alarme, no máximo': 'Suena al volumen de alarma, al máximo',
  'Soneca do alarme': 'Posponer alarma',
  'Tempo ao tocar em “Daqui a X min”': 'Tiempo al tocar “Posponer X min”',
  'Permissões do alarme': 'Permisos de alarma',
  'Popup em tela cheia · Xiaomi · bateria': 'Popup a pantalla completa · Xiaomi · batería',
  Anúncios: 'Anuncios',
  'Anúncios removidos': 'Anuncios eliminados',
  'Premium liberado por convite do desenvolvedor': 'Premium otorgado por invitación del desarrollador',
  'Obrigado pelo apoio! Sem anúncios para sempre': '¡Gracias por tu apoyo! Sin anuncios para siempre',
  'Premium por convite': 'Premium por invitación',
  'Remover anúncios para sempre': 'Quitar anuncios para siempre',
  'Pagamento único pela Play Store': 'Pago único por Google Play',
  'Entre na sua conta para comprar — o Premium fica vinculado ao seu email': 'Inicia sesión para comprar: el Premium queda vinculado a tu email',
  'Para comprar o Premium, primeiro entre na sua conta Google. O Premium fica vinculado ao email da conta que fez a compra.': 'Para comprar Premium, primero inicia sesión en tu cuenta de Google. El Premium queda vinculado al email de la cuenta que hizo la compra.',
  'Premium comprado · vinculado a {email}': 'Premium comprado · vinculado a {email}',
  'Este aparelho já tem Premium comprado pelo email {email}. Entre com essa conta para usar sem anúncios.': 'Este dispositivo ya tiene Premium comprado por el email {email}. Inicia sesión con esa cuenta para usar sin anuncios.',
  Entrar: 'Iniciar sesión',
  'Pagamento indisponível neste aparelho.': 'El pago no está disponible en este dispositivo.',
  'Este aparelho já tem Premium comprado. Entre com a conta que fez a compra para usar sem anúncios.': 'Este dispositivo ya tiene Premium comprado. Inicia sesión con la cuenta que lo compró para usarlo sin anuncios.',
  IA: 'IA',
  'Chave da IA (gratuita)': 'Clave de IA (gratuita)',
  'Respostas como ChatGPT usando modelos grátis do OpenRouter': 'Respuestas como ChatGPT con modelos gratis de OpenRouter',
  'Como criar a chave': 'Cómo crear la clave',
  'Abrir site': 'Abrir sitio web',
  'tutorial.chave.passo1': 'Toca “Abrir sitio web” abajo: se abrirá el navegador en openrouter.ai',
  'tutorial.chave.passo2': 'Toca “Continue with Google” e inicia sesión con tu cuenta (la misma de la app)',
  'tutorial.chave.passo3': 'En la página de claves, toca “+ Create Key” (mantén marcado “Free models”) y confirma',
  'tutorial.chave.passo4': 'El sitio muestra tu clave (empieza con sk-or-v1-). Mantén pulsada y toca → Copiar',
  'tutorial.chave.passo5': 'Vuelve a la app y pega la clave en el campo de arriba: mantén el dedo en el campo y toca “Pegar”',
  'Entendi!': '¡Entendido!',
  'Versão do App': 'Versión de la app',
  Segurança: 'Seguridad',
  'Bloquear App': 'Bloquear la app',
  'Exigir biometria ao abrir o aplicativo': 'Exigir biometría al abrir la app',
  'Tempo de Bloqueio': 'Tiempo de bloqueo',
  'Janela de carência antes de bloquear': 'Periodo de gracia antes de bloquear',
  Imediato: 'Inmediato',
  Erro: 'Error',
  'Este dispositivo não possui suporte a biometria.': 'Este dispositivo no admite biometría.',
  'Nenhuma biometria (digital ou rosto) cadastrada no sistema.': 'No hay biometría (huella o rostro) registrada en el sistema.',
  'Confirme sua identidade para ativar': 'Confirma tu identidad para activar',
  'Tempo para Bloqueio': 'Tiempo de bloqueo',
  'Após quanto tempo fora do app devemos exigir a biometria?': '¿Después de cuánto tiempo fuera de la app exigimos la biometría?',
  Imediatamente: 'Inmediatamente',
  '{n} minutos': '{n} minutos',
  '{n} min': '{n} min',
  'Quanto tempo o alarme adia ao tocar em "Daqui a X min"?': '¿Cuánto tiempo pospone la alarma al tocar “Posponer X min”?',
  'Toca no volume de alarme do celular, forçado ao máximo': 'Suena al volumen de alarma del móvil, forzado al máximo',
  Clássico: 'Clásico',
  Digital: 'Digital',
  Suave: 'Suave',
  Urgente: 'Urgente',
  Eco: 'Eco',
  Ondas: 'Olas',
  'Bipes de despertador tradicionais': 'Bips de despertador tradicionales',
  'Toque de telefone digital': 'Timbre de teléfono digital',
  'Arpejo calmo para acordar devagar': 'Arpegio tranquilo para despertar despacio',
  'Bipes rápidos e fortes': 'Bips rápidos y fuertes',
  'Melodia de cuco com eco': 'Melodía de cuco con eco',
  'Mar calmo batendo na areia': 'Mar en calma llegando a la arena',
  'Criar sua chave grátis': 'Crea tu clave gratis',
  'Leva 1 minuto e não pede cartão': 'Toma 1 minuto y no pide tarjeta',
  Negrito: 'Negrita',
  Itálico: 'Cursiva',
  Sublinhado: 'Subrayado',
  Tachado: 'Tachado',
  'Lista com marcadores': 'Lista con viñetas',
  'Lista numerada': 'Lista numerada',
  'Gravar áudio': 'Grabar audio',
  'Parar gravação': 'Detener grabación',
  'Inserir imagem': 'Insertar imagen',
  // --- Aba / rodapé ---
  Notas: 'Notas',
  Tarefas: 'Tareas',
  Ajustes: 'Configuración',
  // --- Home / seleção / pastas ---
  Cancelar: 'Cancelar',
  Excluir: 'Eliminar',
  'Excluir itens': 'Eliminar elementos',
  Criar: 'Crear',
  'Criar pasta': 'Crear carpeta',
  'Criar nova pasta...': 'Crear nueva carpeta...',
  'Nova pasta': 'Nueva carpeta',
  Pasta: 'Carpeta',
  'Nome da pasta': 'Nombre de la carpeta',
  'Mover para pasta': 'Mover a carpeta',
  'Renomear pasta': 'Renombrar carpeta',
  Salvar: 'Guardar',
  Sucesso: 'Éxito',
  'Excluir pasta': 'Eliminar carpeta',
  'Apagar {n} item selecionado?': '¿Eliminar {n} elemento seleccionado?',
  'Apagar {n} itens selecionados?': '¿Eliminar {n} elementos seleccionados?',
  'Leva os {n} para dentro': 'Mete los {n} dentro',
  'item selecionado': 'elemento seleccionado',
  'itens selecionados': 'elementos seleccionados',
  '{n} selecionada': '{n} seleccionada',
  '{n} selecionadas': '{n} seleccionadas',
  'Deseja apagar esta nota?': '¿Eliminar esta nota?',
  'Deseja apagar esta lista?': '¿Eliminar esta lista?',
  'Nota sem título': 'Nota sin título',
  'Lista sem título': 'Lista sin título',
  'sem título': 'sin título',
  'Toque para editar...': 'Toca para editar...',
  'Nenhuma nota encontrada': 'No se encontraron notas',
  'Procurar em suas notas...': 'Buscar en tus notas...',
  'Comece a organizar suas ideias': 'Empieza a organizar tus ideas',
  'Comece a escrever...': 'Empieza a escribir...',
  'Usar senha': 'Usar contraseña',
  'Nada foi gravado.': 'No se grabó nada.',
  'Mover áudio': 'Mover audio',
  'Armazenamento no Drive': 'Almacenamiento en Drive',
  'Dados do app na nuvem': 'Datos de la app en la nube',
  'Não foi possível conectar ao armazenamento do Drive.': 'No se pudo conectar al almacenamiento de Drive.',
  'Tentar novamente': 'Intentar de nuevo',
  'Mostrando dados anteriores. Toque para atualizar.': 'Mostrando datos anteriores. Toca para actualizar.',
  'Não foi possível atualizar. Toque para tentar de novo.': 'No se pudo actualizar. Toca para intentarlo de nuevo.',
  'Armazenamento quase cheio ({pct}%) — libere espaço para o app continuar fazendo backup.': 'Almacenamiento casi lleno ({pct}%) — libera espacio para que la app siga haciendo copias.',
  'sem limite': 'sin límite',
  'Conta com armazenamento ilimitado do Drive.': 'Esta cuenta tiene almacenamiento ilimitado de Drive.',
  '{n} GB': '{n} GB',
  '{n} MB': '{n} MB',
  '{n} KB': '{n} KB',
  'item salvo': 'elemento guardado',
  'itens salvos': 'elementos guardados',
  '{n} itens salvos': '{n} elementos guardados',
  '{n} itens na lista': '{n} elementos en la lista',
  'Toque no + para criar sua primeira nota': 'Toca + para crear tu primera nota',
  'Nenhuma pasta ainda — crie a primeira!': 'Aún no hay carpetas: ¡crea la primera!',
  'Organize suas notas e listas em pastas': 'Organiza tus notas y listas en carpetas',
  'Guia Rápido': 'Guía rápida',
  'Arraste para a': 'Desliza hacia la',
  Direita: 'derecha',
  Esquerda: 'izquierda',
  'para fixar itens no topo': 'para fijar elementos arriba',
  'para excluir uma nota': 'para eliminar una nota',
  'Suas notas são salvas': 'Tus notas se guardan',
  automaticamente: 'automáticamente',
  'na sua conta Google': 'en tu cuenta de Google',
  'Conectado como {nome}': 'Conectado como {nome}',
  'Conectado como {nome}. {quantidade} itens criados deslogado foram transferidos para sua conta.': 'Conectado como {nome}. {quantidade} ítems creados sin sesión se transfirieron a tu cuenta.',
  'Apagar backups da nuvem': 'Eliminar copias de seguridad de la nube',
  'Apagar todos os dados': 'Borrar todos los datos',
  'Isso exclui PERMANENTEMENTE do aparelho todas as notas, listas, pastas, tarefas e lembretes — e também o backup na nuvem da conta logada. NÃO dá para desfazer.': 'Esto borra PERMANENTEMENTE del dispositivo todas las notas, listas, carpetas, tareas y recordatorios — y también la copia de seguridad en la nube de la cuenta conectada. NO se puede deshacer.',
  'Digite para confirmar': 'Escribe para confirmar',
  'Digite APAGAR para confirmar a exclusão de todos os dados.': 'Escribe BORRAR para confirmar el borrado de todos los datos.',
  APAGAR: 'BORRAR',
  'Apagando...': 'Borrando...',
  'Todos os dados foram apagados.': 'Todos los datos han sido borrados.',
  'Não foi possível apagar tudo. Tente novamente.': 'No se pudo borrar todo. Inténtalo de nuevo.',
  Continuar: 'Continuar',
  'Apagar backups': 'Eliminar copias de seguridad',
  'Isso vai excluir PERMANENTEMENTE o backup na nuvem desta conta. As notas no aparelho não serão afetadas. Deseja continuar?': 'Esto eliminará PERMANENTEMENTE la copia de seguridad en la nube de esta cuenta. Las notas del dispositivo no se verán afectadas. ¿Continuar?',
  'Apagar tudo': 'Eliminar todo',
  'Backups apagados da nuvem.': 'Copias de seguridad eliminadas de la nube.',
  'Você precisa de internet para apagar os backups.': 'Necesitas internet para eliminar las copias de seguridad.',
  'Falha ao apagar os backups.': 'Error al eliminar las copias de seguridad.',
  Login: 'Iniciar sesión',
  'Entrar com Google': 'Iniciar sesión con Google',
  Sair: 'Cerrar sesión',
  'Trocar Conta': 'Cambiar de cuenta',
  Usuário: 'Usuario',
  Offline: 'Sin conexión',
  'Sem sincronização': 'Sin sincronizar',
  'O login não foi concluído.': 'El inicio de sesión no se completó.',
  'Login não concluído. Tente novamente.': 'Inicio de sesión no completado. Inténtalo de nuevo.',
  'Falha no login': 'Error al iniciar sesión',
  'Deseja realmente desconectar?': '¿De verdad quieres cerrar la sesión?',
  'Você está offline. Conecte-se à internet para trocar de conta.': 'Estás sin conexión. Conéctate a internet para cambiar de cuenta.',
  'Você precisa de internet para restaurar.': 'Necesitas internet para restaurar.',
  'Dados restaurados!': '¡Datos restaurados!',
  'Falha ao restaurar.': 'No se pudo restaurar.',
  'Desconectado.': 'Sesión cerrada.',
  // --- Editor (chrome + lembretes) ---
  'Gravando...': 'Grabando...',
  Pronto: 'Listo',
  Editar: 'Editar',
  Título: 'Título',
  'Lembrete de revisão': 'Recordatorio de revisión',
  'Me lembre de ver esta nota': 'Recuérdame revisar esta nota',
  'A cada X dias': 'Cada X días',
  'Dias da semana': 'Días de la semana',
  Horário: 'Hora',
  Data: 'Fecha',
  Escolher: 'Elegir',
  Remover: 'Quitar',
  'Falta o dia': 'Falta la fecha',
  'Escolha a data do lembrete.': 'Elige la fecha del recordatorio.',
  'Faltam os dias': 'Faltan los días',
  'Escolha pelo menos um dia da semana.': 'Elige al menos un día de la semana.',
  'Horário no passado': 'Hora ya pasada',
  'Escolha uma data e horário futuros para o lembrete.': 'Elige una fecha y hora futuras para el recordatorio.',
  'Permissão negada.': 'Permiso denegado.',
  'Permissão necessária.': 'Permiso necesario.',
  'Não foi possível iniciar a gravação.': 'No se pudo iniciar la grabación.',
  'Falha ao salvar o áudio.': 'No se pudo guardar el audio.',
  'Não foi possível carregar a imagem.': 'No se pudo cargar la imagen.',
  'Notificações desativadas': 'Notificaciones desactivadas',
  'Permita as notificações nas configurações do aparelho para receber os lembretes das tarefas.': 'Permite las notificaciones en la configuración del dispositivo para recibir los recordatorios de las tareas.',
  'Confirme para remover a proteção desta nota': 'Confirma para quitar la protección de esta nota',
  // --- Editor: modal da IA ---
  'NotaIA': 'NotaIA',
  'Pergunte sobre suas notas': 'Pregunta sobre tus notas',
  Perguntar: 'Preguntar',
  Resumo: 'Resumen',
  'Pergunte sobre suas notas...': 'Pregunta sobre tus notas...',
  'A conversa com IA precisa de chave': 'La conversación con IA necesita una clave',
  'Adicione sua chave gratuita em\nAjustes → IA para conversar com a IA de verdade.': 'Añade tu clave gratuita en\nConfiguración → IA para hablar con la IA de verdad.',
  'Ir para Ajustes': 'Ir a Configuración',
  'Pergunte qualquer coisa sobre suas notas. ✨\nEx.: «Quanto custa o arroz?» ou «Qual a data da festa?»': 'Pregunta lo que quieras sobre tus notas. ✨\nEj.: «¿Cuánto cuesta el arroz?» o «¿Cuál es la fecha de la fiesta?»',
  'Resumindo…': 'Resumiendo…',
  'Gerar resumo com IA': 'Generar resumen con IA',
  'Lembrete em {data} às {hora}': 'Recordatorio el {data} a las {hora}',
  'Revisar a cada {n} dias às {hora}': 'Revisar cada {n} días a las {hora}',
  'Revisar às {hora}': 'Revisar a las {hora}',
  'Revisar às {dias}, às {hora}': 'Revisar los {dias} a las {hora}',
  // --- Editor de listas ---
  LISTA: 'LISTA',
  'Título da lista': 'Título de la lista',
  'Adicionar item...': 'Añadir elemento...',
  'Progresso da lista': 'Progreso de la lista',
  'Toque em um item para marcar como feito': 'Toca un elemento para marcarlo como hecho',
  'Sua lista está vazia': 'Tu lista está vacía',
  'Adicione o primeiro item acima para começar.': 'Añade el primer elemento arriba para empezar.',
  'Concluído': 'Hecho',
  Pendente: 'Pendiente',
  'Nova Lista': 'Nueva lista',
  // --- Aba de tarefas ---
  'Um passo de cada vez': 'Un paso a la vez',
  'O que precisa ser feito?': '¿Qué hay que hacer?',
  'CONCLUÍDAS': 'HECHAS',
  'Tudo limpo por aqui!': '¡Todo limpio por aquí!',
  'Adicione sua primeira tarefa acima.': 'Añade tu primera tarea arriba.',
  'Uma vez': 'Una vez',
  Diária: 'Diaria',
  Domingo: 'Domingo',
  Segunda: 'Lunes',
  Terça: 'Martes',
  Quarta: 'Miércoles',
  Quinta: 'Jueves',
  Sexta: 'Viernes',
  Sábado: 'Sábado',
  'Vou fazer': 'Lo haré',
  'Deixar para depois': 'Dejarlo para después',
  'Está na hora de revisar esta nota!': '¡Es hora de revisar esta nota!',
  'Está na hora de fazer isso!': '¡Es hora de hacerlo!',
  'Daqui a {n} min': 'Dentro de {n} min',
  'Está na hora de: {titulo}': 'Es hora de: {titulo}',
  'Lembrete: {titulo}': 'Recordatorio: {titulo}',
  'Está na hora de revisar esta nota': 'Es hora de revisar esta nota',
  'Revisado': 'Revisado',
  // --- Pasta (tela interna) ---
  'Pasta vazia': 'Carpeta vacía',
  'Toque no + para criar uma nota ou lista aqui dentro': 'Toca + para crear una nota o lista aquí',
  NOTAS: 'NOTAS',
  LISTAS: 'LISTAS',
  'Nenhum resultado': 'Sin resultados',
  'Nenhum item encontrado para &quot;{busca}&quot;': 'No se encontraron elementos para &quot;{busca}&quot;',
  Fixar: 'Fijar',
  'Dê um novo nome para esta pasta': 'Ponle un nuevo nombre a esta carpeta',
  '{n} item na pasta': '{n} elemento en la carpeta',
  '{n} itens na pasta': '{n} elementos en la carpeta',
  'Procurar nesta pasta...': 'Buscar en esta carpeta...',
  'Excluir a pasta &quot;{nome}&quot;? As notas e listas dela voltam para a lista principal.': '¿Eliminar la carpeta &quot;{nome}&quot;? Sus notas y listas vuelven a la lista principal.',
  'Apagar a nota &quot;{titulo}&quot;?': '¿Eliminar la nota &quot;{titulo}&quot;?',
  'Apagar a lista &quot;{titulo}&quot;?': '¿Eliminar la lista &quot;{titulo}&quot;?',
  'Apagar {n} {qtd} selecionado{s}?': '¿Eliminar {n} {qtd} seleccionado{s}?',
  // --- Feedback ---
  'Como está usando o app?': '¿Cómo estás usando la app?',
  'Seu feedback ajuda a melhorar o Simple Notes. Leva menos de um minuto!': 'Tus comentarios ayudan a mejorar Simple Notes. ¡Toma menos de un minuto!',
  'Avaliar no Google Play': 'Valorar en Google Play',
  'Enviar feedback por e-mail': 'Enviar comentarios por correo',
  'Agora não': 'Ahora no',
  'Feedback — Simple Notes': 'Comentarios — Simple Notes',
  'App Bloqueado': 'App Bloqueada',
  'Desbloquear': 'Desbloquear',
  'Toque no botão abaixo para acessar suas notas, tarefas e anotações.': 'Toca el botón de abajo para acceder a tus notas, tareas y anotaciones.',
  'Bloqueio automático: imediato ao sair do app': 'Bloqueo automático: inmediato al salir de la app',
  'Bloqueio automático: após {n} min fora do app': 'Bloqueo automático: después de {n} min fuera de la app',
  'Acesse suas informações': 'Accede a tu información',
  'Usar senha do dispositivo': 'Usar contraseña del dispositivo',
  'Verificando permissões...': 'Verificando permisos...',
  'Abrir': 'Abrir',
  'Notificações ativadas': 'Notificaciones activadas',
  'O app pode tocar o som do alarme': 'La app puede reproducir el sonido de la alarma',
  'O app precisa da permissão para tocar o alarme': 'La app necesita permiso para reproducir la alarma',
  'Alarme exato': 'Alarma exacta',
  'O alarme dispara na hora certa': 'La alarma suena a tiempo',
  'Sem isso, o alarme pode atrasar alguns minutos': 'Sin esto, la alarma puede retrasarse unos minutos',
  'Exibir pop-ups em segundo plano (MIUI)': 'Mostrar ventanas emergentes en segundo plano (MIUI)',
  'Popup liberado para abrir fora do app': 'Ventana emergente permitida para abrir fuera de la app',
  'Essencial no Xiaomi para o alarme abrir como popup (não só notificação)': 'Esencial en Xiaomi para que la alarma se abra como ventana emergente (no solo notificación)',
  'Popup sobre outros apps': 'Ventana emergente sobre otras apps',
  'O alarme abre por cima de tudo, mesmo com a tela ligada': 'La alarma se abre por encima de todo, incluso con la pantalla encendida',
  'Permite o alarme abrir por cima de outros apps': 'Permite que la alarma se abra sobre otras apps',
  'Tela cheia (Android 14+)': 'Pantalla completa (Android 14+)',
  'Pode abrir por cima de tudo, mesmo bloqueado': 'Puede abrirse por encima de todo, incluso bloqueado',
  'Ative em Ajustes → Acesso especial → Tela cheia': 'Actívalo en Ajustes → Acceso especial → Pantalla completa',
  'Otimização de bateria': 'Optimización de batería',
  'Sem restrições — alarme toca com o app fechado': 'Sin restricciones — la alarma suena con la app cerrada',
  'Defina "Sem restrições" para o alarme tocar com o app fechado': 'Configura "Sin restricciones" para que la alarma suene con la app cerrada',
  'Iniciar automaticamente (Autostart)': 'Iniciar automáticamente (Autostart)',
  'Garante que o alarme dispare com o app fechado': 'Garantiza que la alarma suene con la app cerrada',
  'Ajustes → Apps → Gerenciar apps → Simple Notes → Iniciar automaticamente': 'Ajustes → Apps → Gestionar apps → Simple Notes → Iniciar automáticamente',
  'Notificações na tela de bloqueio': 'Notificaciones en la pantalla de bloqueo',
  'Mostra o alarme com o celular bloqueado': 'Muestra la alarma con el teléfono bloqueado',
  'Ajustes → Notificações → Na tela de bloqueio → Mostrar tudo': 'Ajustes → Notificaciones → En la pantalla de bloqueo → Mostrar todo',
  'No Android, o alarme só abre em POPUP (por cima de outros apps) se o app tiver as permissões abaixo. Em aparelhos Xiaomi (MIUI/HyperOS) são necessários alguns passos extras.': 'En Android, la alarma solo se abre en POPUP (sobre otras apps) si la app tiene los permisos de abajo. En dispositivos Xiaomi (MIUI/HyperOS) se necesitan algunos pasos extra.',
  'Com a permissão de popup (sobreposição) ativada, o alarme abre por cima de tudo — mesmo com a tela ligada. Sem ela: com a tela bloqueada/desligada abre em tela cheia; com a tela ligada mostra apenas um aviso no topo (toque nele para abrir o alarme).': 'Con el permiso de ventana emergente (superposición) activado, la alarma se abre por encima de todo — incluso con la pantalla encendida. Sin él: con la pantalla bloqueada/apagada se abre a pantalla completa; con la pantalla encendida solo muestra un aviso arriba (toca para abrir la alarma).',
  'Dispositivo Xiaomi / MIUI detectado — ative os itens abaixo para o popup funcionar': 'Dispositivo Xiaomi / MIUI detectado — activa los elementos de abajo para que funcione la ventana emergente',
  'Dica: se ainda assim o popup não abrir, verifique também em Ajustes → Bateria → Gerenciar bateria do aparelho se o app está como “Sem restrições” (o nome varia por fabricante: Samsung, Xiaomi, Motorola, etc.).': 'Consejo: si la ventana emergente aún no se abre, revisa también en Ajustes → Batería → Administrar batería si la app está como "Sin restricciones" (el nombre varía según el fabricante: Samsung, Xiaomi, Motorola, etc.).',
  'Apagar': 'Eliminar',
  'Apagar áudio': 'Eliminar audio',
  'Deseja remover este áudio da nota?': '¿Quieres quitar este audio de la nota?',
  'Gravação de áudio': 'Grabación de audio',
  'Pausar áudio': 'Pausar audio',
  'Reproduzir áudio': 'Reproducir audio',
  '“Tela cheia” do Android 14+': '“Pantalla completa” de Android 14+',
  '“Exibir pop-ups em segundo plano” do MIUI': '“Mostrar ventanas emergentes en segundo plano” de MIUI',
  '“Exibir sobre outros apps”': '“Mostrar sobre otras apps”',
  'Popup do alarme bloqueado': 'Ventana emergente de alarma bloqueada',
  'Para o alarme abrir em POPUP (por cima de outros apps, mesmo com o celular bloqueado), ative: {itens}.': 'Para que la alarma se abra en POPUP (sobre otras apps, incluso con el teléfono bloqueado), activa: {itens}.',
  ' No Xiaomi, ative também “Iniciar automaticamente” e “Sem restrições” na bateria.': ' En Xiaomi, activa también “Iniciar automáticamente” y “Sin restricciones” en la batería.',
  'Abrir permissões': 'Abrir permisos',
  // --- DESKTOP (interface do PC) ---
  'Todas': 'Todas',
  'Fixadas': 'Fijadas',
  'NAVEGAR': 'NAVEGAR',
  'PASTAS': 'CARPETAS',
  '+ Nova': '+ Nueva',
  'Desconectado': 'Desconectado',
  'Faça login para vincular ao celular': 'Inicia sesión para vincular con el teléfono',
  'Local apenas': 'Solo local',
  'Conectar Google': 'Conectar Google',
  'Sincronizar': 'Sincronizar',
  'Buscar…': 'Buscar…',
  '0 itens': '0 ítems',
  'Nova nota': 'Nueva nota',
  '+ Lista': '+ Lista',
  '0 selecionados': '0 seleccionados',
  'Clique nos cards para selecionar': 'Haz clic en las tarjetas para seleccionar',
  'Selecionar todos': 'Seleccionar todo',
  'Mover…': 'Mover…',
  'nova nota': 'nueva nota',
  'buscar': 'buscar',
  'fechar editor': 'cerrar editor',
  'clique para selecionar': 'clic para seleccionar',
  'Adicionar': 'Añadir',
  'Assistente IA': 'Asistente IA',
  'Converse sobre suas notas': 'Conversa sobre tus notas',
  'Dica: a IA usa suas notas e tarefas como contexto. Sem internet, faz busca local.': 'Consejo: la IA usa tus notas y tareas como contexto. Sin internet, busca localmente.',
  'Pergunte sobre suas notas…': 'Pregunta sobre tus notas…',
  'Enviar': 'Enviar',
  'Ajustes do app no PC': 'Ajustes de la app en PC',
  'Tema escuro': 'Tema oscuro',
  'OLED no PC, igual ao celular': 'OLED en PC, igual al teléfono',
  'App e assistente de IA': 'App y asistente de IA',
  'Vincular com o celular': 'Vincular con el teléfono',
  'Faça login com a mesma conta do celular': 'Inicia sesión con la misma cuenta del teléfono',
  'Sincronização Drive': 'Sincronización Drive',
  'Sincronizar agora': 'Sincronizar ahora',
  'Inteligência Artificial': 'Inteligencia Artificial',
  'Chave da IA (OpenRouter)': 'Clave de IA (OpenRouter)',
  'Respostas como ChatGPT com modelos grátis': 'Respuestas como ChatGPT con modelos gratis',
  'Bloquear app': 'Bloquear app',
  'PIN de 4 dígitos ao abrir o aplicativo': 'PIN de 4 dígitos al abrir la aplicación',
  'PIN': 'PIN',
  'Nenhum PIN definido': 'Sin PIN definido',
  'Definir PIN': 'Definir PIN',
  'Tempo para bloquear': 'Tiempo para bloquear',
  'Janela antes de pedir o PIN': 'Ventana antes de pedir el PIN',
  'Soneca': 'Siesta',
  'Tempo do "Daqui a X min"': 'Tiempo de "En X min"',
  'Usado na notificação do PC': 'Usado en la notificación del PC',
  'Dados': 'Datos',
  'Apagar tudo?': '¿Eliminar todo?',
  'Digite APAGAR para confirmar:': 'Escribe ELIMINAR para confirmar:',
  'Apagar TUDO': 'Eliminar TODO',
  'Digite o nome da pasta': 'Escribe el nombre de la carpeta',
  'Renomear': 'Renombrar',
  'Mover itens': 'Mover ítems',
  'Mover': 'Mover',
  'Defina o PIN': 'Define el PIN',
  '4 dígitos numéricos': '4 dígitos numéricos',
  'Limpar': 'Limpiar',
  'App bloqueado': 'App bloqueada',
  'Digite o PIN de 4 dígitos — clique ou use o teclado': 'Escribe el PIN de 4 dígitos — clic o teclado',
  'Lembrete': 'Recordatorio',
  'Inserir áudio': 'Insertar audio',
  'Escreva sua nota…': 'Escribe tu nota…',
  'Progresso': 'Progreso',
  'Clique no quadrado para marcar como feito · arraste ⋮ para reordenar': 'Haz clic en el cuadro para marcar como hecho · arrastra ⋮ para reordenar',
  'Adicionar item… (Enter)': 'Añadir ítem… (Enter)',
  'Fechar': 'Cerrar',
  'Minimizar': 'Minimizar',
  'Maximizar': 'Maximizar',
  'Fechar janela': 'Cerrar ventana',
  'Sincronizar com o Drive': 'Sincronizar con Drive',
  'Sincronizando · {n} anexo(s) pendente(s)': 'Sincronizando · {n} adjunto(s) pendiente(s)',
  'Sincronizando…': 'Sincronizando…',
  'Falha ao sincronizar — tentando de novo': 'Error al sincronizar — reintentando',
  // --- IA: proposta de edição (confirmação antes de aplicar) ---
  'Quero editar esta nota': 'Quiero editar esta nota',
  'Título novo:': 'Título nuevo:',
  'Aplicar edición': 'Aplicar edición',
  'Aplicando…': 'Aplicando…',
  '✅ Edición aplicada en la nota.': '✅ Edición aplicada en la nota.',
  'Não permitir': 'No permitir',
  'Permitir': 'Permitir',
  'Aplicar este texto na nota?': '¿Aplicar este texto en la nota?',
  '✅ Conteúdo aplicado na nota.': '✅ Contenido aplicado en la nota.',
  'Cancelar alteração da IA': 'Cancelar el cambio de la IA',
  '↩️ Alteração cancelada — a nota voltou ao que era.': '↩️ Cambio cancelado — la nota volvió a como estaba.',
  // --- Desktop: sistema (auto-start + bandeja) ---
  'Sistema': 'Sistema',
  'Iniciar com o Windows': 'Iniciar con Windows',
  'Abre sozinho ao ligar o PC — fica na bandeja e os alarmes tocam mesmo em segundo plano': 'Se abre solo al encender la PC — queda en la bandeja y las alarmas suenan incluso en segundo plano',
  'Minimizar para a bandeja': 'Minimizar a la bandeja',
  'Fechar só esconde a janela — alarmes continuam tocando; saia de verdade pelo ícone da bandeja': 'Cerrar solo oculta la ventana — las alarmas siguen sonando; sal de verdad desde el icono de la bandeja',
  'Sempre ativo': 'Siempre activo',
  // --- Desktop: textos de interface (renderizadores JS) ---
  'A IA não devolveu a edição pronta. Abra a nota que deseja alterar e peça de novo.': 'La IA no devolvió la edición lista. Abre la nota que quieres cambiar y pídelo de nuevo.',
  'Alterar PIN': 'Cambiar PIN',
  'Alteração cancelada — voltou ao que era.': 'Cambio cancelado — volvió a como estaba.',
  'Alteração da IA cancelada': 'Cambio de la IA cancelado',
  'Apagado localmente (nuvem falhou)': 'Borrado localmente (la nube falló)',
  'Apagar TUDO deste PC (local apenas). Digite APAGAR para confirmar.': 'Borrar TODO de esta PC (solo local). Escribe APAGAR para confirmar.',
  'Apagar TUDO deste PC? Digite APAGAR para confirmar.': '¿Borrar TODO de esta PC? Escribe APAGAR para confirmar.',
  'Apagar TUDO do PC e da nuvem': 'Borrar TODO del PC y de la nube',
  'Ações em lote': 'Acciones en lote',
  'Concluída': 'Completada',
  'Conectado! Sincronizando…': '¡Conectado! Sincronizando…',
  'Configure o client_secret.txt e faça login': 'Configura client_secret.txt e inicia sesión',
  'Crie sua primeira nota — ela aparece no celular após sincronizar.': 'Crea tu primera nota — aparecerá en el móvil tras sincronizar.',
  'Desbloqueado': 'Desbloqueado',
  'Desfixados': 'Desfijados',
  'Digite APAGAR para confirmar': 'Escribe APAGAR para confirmar',
  'Digite novamente': 'Escribe de nuevo',
  'Digite o nome da nova pasta': 'Escribe el nombre de la nueva carpeta',
  'Digite o título da tarefa': 'Escribe el título de la tarea',
  'Digite um nome': 'Escribe un nombre',
  'Edição aplicada.': 'Edición aplicada.',
  'Excluir tarefa': 'Eliminar tarea',
  'Excluído': 'Eliminado',
  'Falha ao apagar': 'Error al borrar',
  'Falha ao enviar — tentando de novo': 'Error al enviar — reintentando',
  'Falha ao sincronizar': 'Error al sincronizar',
  'Fixada': 'Fijada',
  'Gerenciar pasta': 'Gestionar carpeta',
  'IA não carregada': 'IA no cargada',
  'Item adicionado': 'Elemento añadido',
  'Item não encontrado': 'Elemento no encontrado',
  'Lista': 'Lista',
  'Nenhum backup no Drive — este PC vira a fonte': 'Sin copia en Drive — esta PC será la fuente',
  'No celular: Ajustes → IA → Como criar a chave (tutorial). No PC: mesma chave do OpenRouter': 'En el móvil: Ajustes → IA → Cómo crear la clave (tutorial). En el PC: la misma clave de OpenRouter',
  'Nota criada': 'Nota creada',
  'Notas voltam para Todas.': 'Las notas vuelven a Todas.',
  'Notas, listas e tarefas serão perdidas. Digite APAGAR para confirmar.': 'Se perderán notas, listas y tareas. Escribe APAGAR para confirmar.',
  'Notificação + som disparados': 'Notificación + son activados',
  'Nova lista': 'Nueva lista',
  'Novo PIN': 'Nuevo PIN',
  'Novo item': 'Nuevo elemento',
  'Não consegui alterar.': 'No pude aplicar el cambio.',
  'Não encontrei a nota/lista que a IA indicou para editar.': 'No encontré la nota/lista que la IA indicó.',
  'Não vai mais iniciar com o Windows': 'Ya no se iniciará con Windows',
  'PIN definido (4 dígitos) — toque para alterar': 'PIN definido (4 dígitos) — haz clic para cambiar',
  'PINs não conferem': 'Los PIN no coinciden',
  'Para alterar — use teclado ou clique': 'Para cambiar — usa el teclado o haz clic',
  'Pasta criada': 'Carpeta creada',
  'Pasta excluída': 'Carpeta eliminada',
  'Pasta renomeada': 'Carpeta renombrada',
  'Quer editar esta lista': '¿Editar esta lista?',
  'Quer editar esta nota': '¿Editar esta nota?',
  'Renomeie a pasta ou exclua (notas voltam para Todas)': 'Renombra la carpeta o bórrala (las notas vuelven a Todas)',
  'Salvar nome': 'Guardar nombre',
  'Salvo · sincronizando…': 'Guardado · sincronizando…',
  'Selecione a pasta de destino': 'Selecciona la carpeta de destino',
  'Sincronizado com o Drive': 'Sincronizado con Drive',
  'Sincronizado com o celular': 'Sincronizado con el móvil',
  'Tarefa criada · alarme agendado': 'Tarea creada · alarma programada',
  'Tarefa excluída': 'Tarea eliminada',
  'Tema claro': 'Tema claro',
  'Texto aplicado na nota.': 'Texto aplicado en la nota.',
  'Vai iniciar com o Windows': 'Se iniciará con Windows',
  'Adicione sua primeira tarefa acima — o alarme toca no horário mesmo com o app minimizado.': 'Añade tu primera tarea arriba — la alarma suena a la hora incluso con la app minimizada.',
  'Sem pasta (Todas)': 'Sin carpeta (Todas)',
  'Mover {n} item(ns) para:': 'Mover {n} elemento(s) a:',
  'Apagar {n} item(ns)? Esta ação não pode ser desfeita.': '¿Borrar {n} elemento(s)? Esto no se puede deshacer.',
  'Apagar {n} item(ns) selecionado(s)?': '¿Borrar {n} elemento(s) seleccionado(s)?',
  'Excluir pasta "{nome}"? Notas voltam para Todas.': '¿Eliminar la carpeta "{nome}"? Las notas vuelven a Todas.',
  'Excluir tarefa "{nome}"?': '¿Eliminar la tarea "{nome}"?',
  'Excluir "{nome}"?': '¿Eliminar "{nome}"?',
  'Áudio inserido': 'Audio insertado',
  'Anexo salvo — enviando para o Drive': 'Adjunto guardado — enviando a Drive',
  // --- App de DESKTOP (PC) ---
  'Imagem inserida': 'Imagen insertada',
  'Tente outro termo.': 'Prueba otro término.',
  '★ Fixada': '★ Fijada',
  '☆ Fixar': '☆ Fijar',
  '· Fixada': '· Fijada',
  'Apagados': 'Eliminados',
  'Fixados': 'Fijados',
  'Excluir?': '¿Eliminar?',
  '4 dígitos numéricos — clique ou digite': '4 dígitos numéricos — haz clic o escribe',
  'Digite o PIN atual': 'Escribe el PIN actual',
  'Confirme o PIN': 'Confirma el PIN',
  'PIN salvo': 'PIN guardado',
  'PIN incorreto': 'PIN incorrecto',
  '4 dígitos': '4 dígitos',
  'Idioma:': 'Idioma:',
  'Não consegui alterar': 'No se pudo cambiar',
  'Chave salva': 'Clave guardada',
  'Chave removida': 'Clave eliminada',
  'Movidos': 'Movidos',
  'Apagando…': 'Eliminando…',
  'Tudo apagado': 'Todo eliminado',
  'Abrindo navegador…': 'Abriendo el navegador…',
  'Login cancelado': 'Inicio de sesión cancelado',
  'Pensando…': 'Pensando…',
  'Erro:': 'Error:',
  '✅ Edição aplicada.': '✅ Edición aplicada.',
  '↩️ Alteração cancelada — voltou ao que era.': '↩️ Cambio cancelado — volvió a como estaba.',
  '✅ Texto aplicado na nota.': '✅ Texto aplicado en la nota.',
  'IA editou:': 'La IA editó:',
  'Soneca:': 'Siesta:',
  'URI copiado:': 'URI copiado:',
  'Nenhuma pasta': 'Ninguna carpeta',
  '🎙 áudio': '🎙 audio',
  '🖼 imagem': '🖼 imagen',
  'Protegida': 'Protegida',
  'Nota': 'Nota',
  'Sua lista está vazia — adicione o primeiro item acima.': 'Tu lista está vacía — añade el primer elemento arriba.',
  'Erro: preload não carregou.': 'Error: el preload no se cargó.',
  '↩️ Cancelar alteração da IA': '↩️ Deshacer cambio de la IA',
  'Sincronizado com o Drive · {hora}': 'Sincronizado con Drive · {hora}',
  'Aplicar este texto na nota: {titulo}': 'Aplicar este texto en la nota: {titulo}',
  'Quer editar esta lista: {titulo}': 'Editar esta lista: {titulo}',
  'Quer editar esta nota: {titulo}': 'Editar esta nota: {titulo}',
  '{n} itens · {m} pendentes': '{n} elementos · {m} pendientes',
  'Apagar TUDO do PC e da nuvem ({email})? Notas, listas e tarefas serão perdidas. Digite APAGAR para confirmar.': '¿Eliminar TODO del PC y de la nube ({email})? Se perderán notas, listas y tareas. Escribe APAGAR para confirmar.',
  'Testar alarme': 'Probar alarma',
  '{n} itens': '{n} elementos',
  '{n} tarefas': '{n} tareas',
  'Arraste': 'Arrastra',
  // --- IA do desktop (FAQ local + fallbacks offline) ---
  'Em Ajustes → Anúncios há "Remover anúncios para sempre" (pagamento único na Play Store). Também existe Premium por convite.': 'En Configuración → Anuncios hay "Quitar anuncios para siempre" (pago único en Google Play). También existe Premium por invitación.',
  'Sim! Em Ajustes → Aparência você alterna o Modo Escuro (OLED no PC, igual ao celular).': '¡Sí! En Configuración → Apariencia cambias el modo oscuro (OLED en el PC, igual que en el celular).',
  'Em Ajustes → Alarme você escolhe o som e a soneca (5 a 60 min). No PC o alarme toca com som do sistema + Web Audio e botão Soneca.': 'En Configuración → Alarma eliges el sonido y la posposición (5 a 60 min). En el PC la alarma suena con el sonido del sistema + Web Audio y botón de posponer.',
  'Em Ajustes → Segurança você define um PIN de 4 dígitos. No PC ele bloqueia ao minimizar/voltar ao app; no celular usa biometria.': 'En Configuración → Seguridad defines un PIN de 4 dígitos. En el PC bloquea al minimizar/volver a la app; en el celular usa biometría.',
  'Entrando com a mesma conta Google no celular e no PC, notas/listas/pastas/tarefas ficam no Drive (backup_notas.json em appDataFolder) e sincronizam com um clique em Sincronizar.': 'Al iniciar sesión con la misma cuenta de Google en el celular y el PC, notas/listas/carpetas/tareas quedan en Drive (backup_notas.json en appDataFolder) y se sincronizan con un clic en Sincronizar.',
  'Na aba Tarefas você cria tarefas com recorrência (uma vez/diária/dias específicos) e horário, com notificação e soneca.': 'En la pestaña Tareas creas tareas con repetición (una vez/diaria/días concretos) y hora, con notificación y posposición.',
  'Na barra lateral, clique em + Nova para criar pasta; clique direito na pasta para renomear/excluir; selecione notas/listas com Ctrl+clique e Mover para outra pasta.': 'En la barra lateral, haz clic en + Nueva para crear una carpeta; clic derecho en la carpeta para renombrar/eliminar; selecciona notas/listas con Ctrl+clic y Mover a otra carpeta.',
  'As listas são checklists com checkbox, marcar/desmarcar e arrastar para reordenar (⋮⋮). Também moram dentro de pastas.': 'Las listas son checklists con casilla, marcar/desmarcar y arrastrar para reordenar (⋮⋮). También viven dentro de carpetas.',
  'No editor da nota, o ícone de sino agenda lembretes (data/hora, a cada X dias ou dias da semana). No PC o lembrete entra como tarefa com alarme.': 'En el editor de la nota, el icono de campana programa recordatorios (fecha/hora, cada X días o días de la semana). En el PC el recordatorio entra como tarea con alarma.',
  'A IA fica em Ajustes → IA: cole a chave gratuita do OpenRouter (botão Como criar a chave) para respostas como ChatGPT. Sem chave, respondo buscando nas suas notas.': 'La IA está en Configuración → IA: pega la clave gratuita de OpenRouter (botón Cómo crear la clave) para respuestas como ChatGPT. Sin clave, respondo buscando en tus notas.',
  'No editor você insere imagem (🖼) e áudio (🎙) — no PC arraste arquivos para dentro da nota ou use Ctrl+V. No celular as imagens vão para o Drive como anexo e são baixadas ao restaurar.': 'En el editor insertas imagen (🖼) y audio (🎙) — en el PC arrastra archivos a la nota o usa Ctrl+V. En el celular las imágenes van a Drive como adjunto y se descargan al restaurar.',
  'Em Ajustes → Aparência → Idioma escolha Português/English/Español — o app e a IA respondem no idioma escolhido.': 'En Configuración → Apariencia → Idioma elige Português/English/Español — la app y la IA responden en el idioma elegido.',
  'Oi! 👋 Sou o NotaIA, seu assistente do Simple Notes. Posso ajudar com notas, listas, tarefas, pastas, lembretes, backup no Drive, modo escuro e PIN. O que quer fazer?': '¡Hola! 👋 Soy NotaIA, tu asistente de Simple Notes. Puedo ayudarte con notas, listas, tareas, carpetas, recordatorios, copia en Drive, modo oscuro y PIN. ¿Qué quieres hacer?',
  'Sou o NotaIA, assistente do Simple Notes 🤖\nAjudo com suas notas, listas, tarefas, pastas, lembretes, backup no Drive, modo escuro e bloqueio por PIN — tudo offline ou com IA online quando há chave configurada. Me diga o que precisa!': 'Soy NotaIA, el asistente de Simple Notes 🤖\nTe ayudo con tus notas, listas, tareas, carpetas, recordatorios, copia en Drive, modo oscuro y bloqueo por PIN — todo sin conexión o con IA en línea cuando hay clave. ¡Dime qué necesitas!',
  'Só consigo ajudar com o conteúdo das suas notas 🙂\n\nPergunte sobre o que escreveu — ex: "resuma minha nota de receita" ou "o que tenho pendente?".': 'Solo puedo ayudar con el contenido de tus notas 🙂\n\nPregunta sobre lo que escribiste — ej.: "resume mi nota de receta" o "¿qué tengo pendiente?".',
  'Encontrei isso nas suas notas:': 'Encontré esto en tus notas:',
  '_(modo offline — adicione a chave gratuita em Configurações → IA para respostas como ChatGPT)_': '_(modo sin conexión — añade la clave gratuita en Configuración → IA para respuestas como ChatGPT)_',
  'Chave de IA inválida. Verifique em Configurações → IA (OpenRouter).': 'Clave de IA no válida. Revísala en Configuración → IA (OpenRouter).',
  'IA em limite de uso. Aguarde um minuto e tente de novo.': 'IA en límite de uso. Espera un minuto y vuelve a intentarlo.',
  'Não consegui conectar à IA online, mas encontrei:': 'No pude conectar con la IA en línea, pero encontré:',
  '_(Verifique a internet ou a chave em Configurações → IA)_': '_(Revisa tu internet o la clave en Configuración → IA)_',
  'Não consegui conectar à IA online. Verifique a internet ou a chave em Configurações → IA.': 'No pude conectar con la IA en línea. Revisa tu internet o la clave en Configuración → IA.',
  'Versão': 'Versión',
  'Vinculado ao celular pelo mesmo backup do Drive em appDataFolder.': 'Vinculado al celular con la misma copia de Drive en appDataFolder.',
  'Remove notas, listas, pastas e tarefas do PC e da nuvem (se logado). Igual ao celular.': 'Elimina notas, listas, carpetas y tareas del PC y de la nube (si iniciaste sesión). Igual que en el celular.',
  'PIN definido em Configurações → Segurança · Backspace apaga': 'PIN definido en Configuración → Seguridad · Retroceso borra',
  'Olá! Pergunte qualquer coisa sobre suas notas. Ex: "resuma minha nota de receita" ou "o que tenho pendente?"': '¡Hola! Pregunta lo que quieras sobre tus notas. Ej.: "resume mi nota de receta" o "¿qué tengo pendiente?"',
  'Mostrar/ocultar': 'Mostrar/ocultar',
  'Testar notificação': 'Probar notificación',
  'Alternar grade/lista': 'Alternar cuadrícula/lista',
  'Grade': 'Cuadrícula',
  'Ctrl + N nova nota · Ctrl + F buscar · Esc fechar editor · Ctrl + clique para selecionar': 'Ctrl + N nueva nota · Ctrl + F buscar · Esc cerrar editor · Ctrl + clic para seleccionar',
};

export const traducoes: Record<Idioma, Record<string, string>> = { pt, en, es };

/**
 * Idioma ativo (espelho do config). Permite localizar strings fora de
 * componentes React (ex.: textos de notificação agendados em módulos puros).
 * O ThemeProvider atualiza este espelho sempre que o idioma muda.
 */
export let idiomaAtual: Idioma = 'pt';
export const definirIdiomaAtual = (i: Idioma) => {
  idiomaAtual = i;
};

/** Traduz uma chave para o idioma ativo (com fallback pt → chave). */
export function tIdioma(
  idioma: Idioma,
  chave: string,
  vars?: Record<string, string | number>
): string {
  let texto = traducoes[idioma][chave] ?? traducoes.pt[chave] ?? chave;
  if (vars) {
    for (const k of Object.keys(vars)) {
      texto = texto.split(`{${k}}`).join(String(vars[k]));
    }
  }
  return texto;
}
