const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('snDesktop', {
  minimizar: () => ipcRenderer.send('janela:minimizar'),
  maximizar: () => ipcRenderer.send('janela:maximizar'),
  fechar: () => ipcRenderer.send('janela:fechar'),
  storeLer: () => ipcRenderer.invoke('store:ler'),
  storeSalvar: (d) => ipcRenderer.invoke('store:salvar', d),
  storeApagarTudo: () => ipcRenderer.invoke('store:apagarTudo'),
  configLer: () => ipcRenderer.invoke('config:ler'),
  configSalvar: (patch) => ipcRenderer.invoke('config:salvar', patch),
  syncBaixar: () => ipcRenderer.invoke('store:sync:baixar'),
  syncMeta: () => ipcRenderer.invoke('store:sync:meta'),
  syncEnviar: (d) => ipcRenderer.invoke('store:sync:enviar', d),
  anexosHidratar: () => ipcRenderer.invoke('store:anexos:hidratar'),
  googleEntrar: () => ipcRenderer.invoke('google:entrar'),
  googleSair: () => ipcRenderer.invoke('google:sair'),
  googleUsuario: () => ipcRenderer.invoke('google:usuario'),
  googleTokens: () => ipcRenderer.invoke('google:tokens'),
  googleTemSecret: () => ipcRenderer.invoke('google:temSecret'),
  googleInfo: () => ipcRenderer.invoke('google:info'),
  alarme: {
    agendar: (id, titulo, quandoMs, recorrencia, horario) => ipcRenderer.invoke('alarme:agendar', { id, titulo, quandoMs, recorrencia, horario }),
    cancelar: (id) => ipcRenderer.invoke('alarme:cancelar', { id }),
    testar: () => ipcRenderer.invoke('alarme:testar'),
  },
  onAlarme: (cb) => ipcRenderer.on('alarme:disparou', (_e, payload) => cb(payload)),
  iniciarComWindowsLer: () => ipcRenderer.invoke('app:iniciarComWindows:ler'),
  iniciarComWindowsSet: (v) => ipcRenderer.invoke('app:iniciarComWindows:set', v),
  versao: () => ipcRenderer.invoke('app:versao'),
});
